### engle 2023 + 2024

In [1]:
import pandas as pd
import numpy as np

engle = pd.read_csv("cf_data/engle_unified_long_from_pdfs.csv")

print(engle.shape)
display(engle.head())
display(engle.columns.tolist())

(414, 42)

,source_paper,source_year,pdf_file,table_id,sample_group,activity_type,star_name,normalized_name,sp_type,age_gyr_raw,...,log_Lx_over_Lbol_unc,log_Llya_over_Lbol_raw,log_Llya_over_Lbol,log_Llya_over_Lbol_unc_raw,log_Llya_over_Lbol_unc,log_RHK_raw,log_RHK,log_RHK_unc_raw,log_RHK_unc,measurement_src
0,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,Pleiades,Pleiades,M0–2V,"0.125 [+0.05, −0.05]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,NGC 2516,NGC 2516,M0–2V,"0.15 [+0.02, −0.02]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,M34,M34,M0–2V,"0.22 [+0.02, −0.02]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,NGC 3532,NGC 3532,M0–2V,"0.30 [+0.05, −0.05]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,M37,M37,M0–2V,"0.52 [+0.06, −0.06]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['source_paper',
 'source_year',
 'pdf_file',
 'table_id',
 'sample_group',
 'activity_type',
 'star_name',
 'normalized_name',
 'sp_type',
 'age_gyr_raw',
 'age_gyr',
 'age_gyr_err_plus',
 'age_gyr_err_minus',
 'age_note_ref',
 'prot_days_raw',
 'prot_days',
 'prot_err_plus',
 'prot_err_minus',
 'prot_note_ref',
 'prot_src',
 'age_determined_via',
 'log_age_gyr_raw',
 'log_age_gyr',
 'log_age_unc_raw',
 'log_age_unc',
 'log_Lx_raw',
 'log_Lx',
 'log_Lx_unc_raw',
 'log_Lx_unc',
 'log_Lx_over_Lbol_raw',
 'log_Lx_over_Lbol',
 'log_Lx_over_Lbol_unc_raw',
 'log_Lx_over_Lbol_unc',
 'log_Llya_over_Lbol_raw',
 'log_Llya_over_Lbol',
 'log_Llya_over_Lbol_unc_raw',
 'log_Llya_over_Lbol_unc',
 'log_RHK_raw',
 'log_RHK',
 'log_RHK_unc_raw',
 'log_RHK_unc',
 'measurement_src']

In [7]:
engle = pd.read_csv("cf_data/engle_unified_long_from_pdfs.csv")

cols = [c for c in engle.columns if any(k in c.lower() for k in ["prot", "age", "err", "unc"])]
print(cols)

display(engle[cols].head(10))

['age_gyr_raw', 'age_gyr', 'age_gyr_err_plus', 'age_gyr_err_minus', 'age_note_ref', 'prot_days_raw', 'prot_days', 'prot_err_plus', 'prot_err_minus', 'prot_note_ref', 'prot_src', 'age_determined_via', 'log_age_gyr_raw', 'log_age_gyr', 'log_age_unc_raw', 'log_age_unc', 'log_Lx_unc_raw', 'log_Lx_unc', 'log_Lx_over_Lbol_unc_raw', 'log_Lx_over_Lbol_unc', 'log_Llya_over_Lbol_unc_raw', 'log_Llya_over_Lbol_unc', 'log_RHK_unc_raw', 'log_RHK_unc']

,age_gyr_raw,age_gyr,age_gyr_err_plus,age_gyr_err_minus,age_note_ref,prot_days_raw,prot_days,prot_err_plus,prot_err_minus,prot_note_ref,...,log_age_unc_raw,log_age_unc,log_Lx_unc_raw,log_Lx_unc,log_Lx_over_Lbol_unc_raw,log_Lx_over_Lbol_unc,log_Llya_over_Lbol_unc_raw,log_Llya_over_Lbol_unc,log_RHK_unc_raw,log_RHK_unc
0,"0.125 [+0.05, −0.05]",0.125,0.05,-0.05,NaN,"2.11 [+2.96, −1.50]a",2.11,2.96,-1.50,a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"0.15 [+0.02, −0.02]",0.150,0.02,-0.02,NaN,"1.80 [+2.93, −1.30]a",1.80,2.93,-1.30,a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"0.22 [+0.02, −0.02]",0.220,0.02,-0.02,NaN,"6.82 [+3.99, −3.99]a",6.82,3.99,-3.99,a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"0.30 [+0.05, −0.05]",0.300,0.05,-0.05,NaN,"10.96 [+5.47, −5.47]b",10.96,5.47,-5.47,b,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"0.52 [+0.06, −0.06]",0.520,0.06,-0.06,NaN,"13.15 [+5.24, −5.24]a",13.15,5.24,-5.24,a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"0.73 [+0.12, −0.12]",0.730,0.12,-0.12,NaN,"16.06 [+2.91, −12.2]c",16.06,2.91,-12.20,c,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"0.89 [+0.15, −0.15]",0.890,0.15,-0.15,NaN,"14.19 [+1.45, −1.45]d",14.19,1.45,-1.45,d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"1.46 [+0.18, −0.18]",1.460,0.18,-0.18,NaN,"18.6 [+4.2, −4.2]e",18.60,4.20,-4.20,e,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"2.50 [+1.82, −0.93]",2.500,1.82,-0.93,NaN,"23.19 [+1.84, −1.84]",23.19,1.84,-1.84,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"2.52 [+1.58, −0.61]",2.520,1.58,-0.61,NaN,"23.27 [+0.04, −0.04]",23.27,0.04,-0.04,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
engle_clean = engle.copy()

# age
if "age_gyr_err_plus" in engle_clean.columns:
    engle_clean["age_err_hi_gyr"] = pd.to_numeric(engle_clean["age_gyr_err_plus"], errors="coerce").abs()

if "age_gyr_err_minus" in engle_clean.columns:
    engle_clean["age_err_lo_gyr"] = pd.to_numeric(engle_clean["age_gyr_err_minus"], errors="coerce").abs()

# prot
if "prot_days_err_plus" in engle_clean.columns:
    engle_clean["prot_err_hi_days"] = pd.to_numeric(engle_clean["prot_days_err_plus"], errors="coerce").abs()

if "prot_days_err_minus" in engle_clean.columns:
    engle_clean["prot_err_lo_days"] = pd.to_numeric(engle_clean["prot_days_err_minus"], errors="coerce").abs()

# log age, if present
if "log_age_yr_err_plus" in engle_clean.columns:
    engle_clean["log_age_err_hi"] = pd.to_numeric(engle_clean["log_age_yr_err_plus"], errors="coerce").abs()

if "log_age_yr_err_minus" in engle_clean.columns:
    engle_clean["log_age_err_lo"] = pd.to_numeric(engle_clean["log_age_yr_err_minus"], errors="coerce").abs()

In [9]:
cols = [c for c in [
    "star_name",
    "source_paper",
    "source_table",
    "age_gyr_raw",
    "age_gyr",
    "age_gyr_err_plus",
    "age_gyr_err_minus",
    "age_err_lo_gyr",
    "age_err_hi_gyr",
    "prot_days_raw",
    "prot_days",
    "prot_days_err_plus",
    "prot_days_err_minus",
    "prot_err_lo_days",
    "prot_err_hi_days",
] if c in engle_clean.columns]

display(engle_clean[cols].head(15))

,star_name,source_paper,age_gyr_raw,age_gyr,age_gyr_err_plus,age_gyr_err_minus,age_err_lo_gyr,age_err_hi_gyr,prot_days_raw,prot_days
0,Pleiades,Engle_2023,"0.125 [+0.05, −0.05]",0.125,0.05,-0.05,0.05,0.05,"2.11 [+2.96, −1.50]a",2.11
1,NGC 2516,Engle_2023,"0.15 [+0.02, −0.02]",0.150,0.02,-0.02,0.02,0.02,"1.80 [+2.93, −1.30]a",1.80
2,M34,Engle_2023,"0.22 [+0.02, −0.02]",0.220,0.02,-0.02,0.02,0.02,"6.82 [+3.99, −3.99]a",6.82
3,NGC 3532,Engle_2023,"0.30 [+0.05, −0.05]",0.300,0.05,-0.05,0.05,0.05,"10.96 [+5.47, −5.47]b",10.96
4,M37,Engle_2023,"0.52 [+0.06, −0.06]",0.520,0.06,-0.06,0.06,0.06,"13.15 [+5.24, −5.24]a",13.15
5,Praesepe/Hyades,Engle_2023,"0.73 [+0.12, −0.12]",0.730,0.12,-0.12,0.12,0.12,"16.06 [+2.91, −12.2]c",16.06
6,NGC 6811,Engle_2023,"0.89 [+0.15, −0.15]",0.890,0.15,-0.15,0.15,0.15,"14.19 [+1.45, −1.45]d",14.19
7,NGC 752,Engle_2023,"1.46 [+0.18, −0.18]",1.460,0.18,-0.18,0.18,0.18,"18.6 [+4.2, −4.2]e",18.60
8,L266-195,Engle_2023,"2.50 [+1.82, −0.93]",2.500,1.82,-0.93,0.93,1.82,"23.19 [+1.84, −1.84]",23.19
9,LP 856-54,Engle_2023,"2.52 [+1.58, −0.61]",2.520,1.58,-0.61,0.61,1.58,"23.27 [+0.04, −0.04]",23.27
10,Ruprecht 147,Engle_2023,"2.6 [+0.4, −0.4]",2.600,0.40,-0.40,0.40,0.40,"22.4 [+2.9, −2.9]f,g",22.40
11,G59-39,Engle_2023,"3.20 [+1.96, −0.93]",3.200,1.96,-0.93,0.93,1.96,"33.82 [+0.07, −0.07]",33.82
12,LP 775-52,Engle_2023,"3.39 [+0.29, −0.20]",3.390,0.29,-0.20,0.20,0.29,"36.90 [+0.10, −0.10]",36.90
13,GJ 2131 A,Engle_2023,"3.47 [+1.69, −1.69]",3.470,1.69,-1.69,1.69,1.69,"34.82 [+0.10, −0.10]",34.82
14,G111-72,Engle_2023,"3.64 [+1.35, −0.68]",3.640,1.35,-0.68,0.68,1.35,"38.96 [+0.13, −0.13]",38.96

In [10]:
cols = [c for c in [
    "star_name",
    "source_paper",
    "prot_days_raw",
    "prot_days",
    "prot_days_err_plus",
    "prot_days_err_minus",
    "prot_err_lo_days",
    "prot_err_hi_days",
] if c in engle_clean.columns]

display(engle_clean[cols].head(10))

         star_name source_paper          prot_days_raw  prot_days
0         Pleiades   Engle_2023   2.11 [+2.96, −1.50]a       2.11
1         NGC 2516   Engle_2023   1.80 [+2.93, −1.30]a       1.80
2              M34   Engle_2023   6.82 [+3.99, −3.99]a       6.82
3         NGC 3532   Engle_2023  10.96 [+5.47, −5.47]b      10.96
4              M37   Engle_2023  13.15 [+5.24, −5.24]a      13.15
5  Praesepe/Hyades   Engle_2023  16.06 [+2.91, −12.2]c      16.06
6         NGC 6811   Engle_2023  14.19 [+1.45, −1.45]d      14.19
7          NGC 752   Engle_2023     18.6 [+4.2, −4.2]e      18.60
8         L266-195   Engle_2023   23.19 [+1.84, −1.84]      23.19
9        LP 856-54   Engle_2023   23.27 [+0.04, −0.04]      23.27

In [11]:
import re
import pandas as pd
import numpy as np

engle_clean = engle_clean.copy()

def extract_trailing_note(x):
    if pd.isna(x):
        return np.nan
    s = str(x).strip()
    m = re.search(r'([a-zA-Z]+)\s*$', s)
    return m.group(1) if m else np.nan

engle_clean["prot_note_ref"] = engle_clean["prot_days_raw"].apply(extract_trailing_note) if "prot_days_raw" in engle_clean.columns else np.nan
engle_clean["age_note_ref"] = engle_clean["age_gyr_raw"].apply(extract_trailing_note) if "age_gyr_raw" in engle_clean.columns else np.nan

display(
    engle_clean[
        [c for c in ["star_name", "prot_days_raw", "prot_note_ref", "age_gyr_raw", "age_note_ref"] if c in engle_clean.columns]
    ].head(15)
)

,star_name,prot_days_raw,prot_note_ref,age_gyr_raw,age_note_ref
0,Pleiades,"2.11 [+2.96, −1.50]a",a,"0.125 [+0.05, −0.05]",NaN
1,NGC 2516,"1.80 [+2.93, −1.30]a",a,"0.15 [+0.02, −0.02]",NaN
2,M34,"6.82 [+3.99, −3.99]a",a,"0.22 [+0.02, −0.02]",NaN
3,NGC 3532,"10.96 [+5.47, −5.47]b",b,"0.30 [+0.05, −0.05]",NaN
4,M37,"13.15 [+5.24, −5.24]a",a,"0.52 [+0.06, −0.06]",NaN
5,Praesepe/Hyades,"16.06 [+2.91, −12.2]c",c,"0.73 [+0.12, −0.12]",NaN
6,NGC 6811,"14.19 [+1.45, −1.45]d",d,"0.89 [+0.15, −0.15]",NaN
7,NGC 752,"18.6 [+4.2, −4.2]e",e,"1.46 [+0.18, −0.18]",NaN
8,L266-195,"23.19 [+1.84, −1.84]",NaN,"2.50 [+1.82, −0.93]",NaN
9,LP 856-54,"23.27 [+0.04, −0.04]",NaN,"2.52 [+1.58, −0.61]",NaN
10,Ruprecht 147,"22.4 [+2.9, −2.9]f,g",g,"2.6 [+0.4, −0.4]",NaN
11,G59-39,"33.82 [+0.07, −0.07]",NaN,"3.20 [+1.96, −0.93]",NaN
12,LP 775-52,"36.90 [+0.10, −0.10]",NaN,"3.39 [+0.29, −0.20]",NaN
13,GJ 2131 A,"34.82 [+0.10, −0.10]",NaN,"3.47 [+1.69, −1.69]",NaN
14,G111-72,"38.96 [+0.13, −0.13]",NaN,"3.64 [+1.35, −0.68]",NaN

In [12]:
engle_clean

,source_paper,source_year,pdf_file,table_id,sample_group,activity_type,star_name,normalized_name,sp_type,age_gyr_raw,...,log_Llya_over_Lbol,log_Llya_over_Lbol_unc_raw,log_Llya_over_Lbol_unc,log_RHK_raw,log_RHK,log_RHK_unc_raw,log_RHK_unc,measurement_src,age_err_hi_gyr,age_err_lo_gyr
0,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,Pleiades,Pleiades,M0–2V,"0.125 [+0.05, −0.05]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,0.05
1,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,NGC 2516,NGC 2516,M0–2V,"0.15 [+0.02, −0.02]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02,0.02
2,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,M34,M34,M0–2V,"0.22 [+0.02, −0.02]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02,0.02
3,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,NGC 3532,NGC 3532,M0–2V,"0.30 [+0.05, −0.05]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,0.05
4,Engle_2023,2023,Engle_2023_ApJL_954_L50.pdf,Table 2,early_benchmarks,NaN,M37,M37,M0–2V,"0.52 [+0.06, −0.06]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.06,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,Engle_2024,2024,Engle_2024_ApJ_960_62.pdf,Table 7,NaN,caii,GJ 581,GJ 581,NaN,NaN,...,NaN,NaN,NaN,−5.487,-5.487,0.425,0.425,NaN,NaN,NaN
410,Engle_2024,2024,Engle_2024_ApJ_960_62.pdf,Table 7,NaN,caii,GJ 699,GJ 699,NaN,NaN,...,NaN,NaN,NaN,−5.490,-5.490,0.634,0.634,NaN,NaN,NaN
411,Engle_2024,2024,Engle_2024_ApJ_960_62.pdf,Table 7,NaN,caii,GJ 273,GJ 273,NaN,NaN,...,NaN,NaN,NaN,−5.273,-5.273,0.520,0.520,NaN,NaN,NaN
412,Engle_2024,2024,Engle_2024_ApJ_960_62.pdf,Table 7,NaN,caii,LP 855-60,LP 855-60,NaN,NaN,...,NaN,NaN,NaN,−5.963,-5.963,0.025,0.025,NaN,NaN,NaN
413,Engle_2024,2024,Engle_2024_ApJ_960_62.pdf,Table 7,NaN,caii,GJ 191,GJ 191,NaN,NaN,...,NaN,NaN,NaN,−5.609,-5.609,0.495,0.495,NaN,NaN,NaN

In [13]:
engle_clean.columns

Index(['source_paper', 'source_year', 'pdf_file', 'table_id', 'sample_group',
       'activity_type', 'star_name', 'normalized_name', 'sp_type',
       'age_gyr_raw', 'age_gyr', 'age_gyr_err_plus', 'age_gyr_err_minus',
       'age_note_ref', 'prot_days_raw', 'prot_days', 'prot_err_plus',
       'prot_err_minus', 'prot_note_ref', 'prot_src', 'age_determined_via',
       'log_age_gyr_raw', 'log_age_gyr', 'log_age_unc_raw', 'log_age_unc',
       'log_Lx_raw', 'log_Lx', 'log_Lx_unc_raw', 'log_Lx_unc',
       'log_Lx_over_Lbol_raw', 'log_Lx_over_Lbol', 'log_Lx_over_Lbol_unc_raw',
       'log_Lx_over_Lbol_unc', 'log_Llya_over_Lbol_raw', 'log_Llya_over_Lbol',
       'log_Llya_over_Lbol_unc_raw', 'log_Llya_over_Lbol_unc', 'log_RHK_raw',
       'log_RHK', 'log_RHK_unc_raw', 'log_RHK_unc', 'measurement_src',
       'age_err_hi_gyr', 'age_err_lo_gyr'],
      dtype='object')

In [14]:
keep_cols = [
    "source_paper",
    "source_year",
    "table_id",
    "star_name",
    "normalized_name",
    "sp_type",
    "age_gyr_raw",
    "age_gyr",
    "age_err_lo_gyr",
    "age_err_hi_gyr",
    "prot_days_raw",
    "prot_days",
    "prot_err_lo_days",
    "prot_err_hi_days",
    "age_determined_via",
]

keep_cols = [c for c in keep_cols if c in engle_clean.columns]

engle_trimmed = engle_clean[keep_cols].copy()

print(engle_trimmed.shape)
display(engle_trimmed.head(20))

(414, 13)

,source_paper,source_year,table_id,star_name,normalized_name,sp_type,age_gyr_raw,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days_raw,prot_days,age_determined_via
0,Engle_2023,2023,Table 2,Pleiades,Pleiades,M0–2V,"0.125 [+0.05, −0.05]",0.125,0.05,0.05,"2.11 [+2.96, −1.50]a",2.11,Cluster
1,Engle_2023,2023,Table 2,NGC 2516,NGC 2516,M0–2V,"0.15 [+0.02, −0.02]",0.150,0.02,0.02,"1.80 [+2.93, −1.30]a",1.80,Cluster
2,Engle_2023,2023,Table 2,M34,M34,M0–2V,"0.22 [+0.02, −0.02]",0.220,0.02,0.02,"6.82 [+3.99, −3.99]a",6.82,Cluster
3,Engle_2023,2023,Table 2,NGC 3532,NGC 3532,M0–2V,"0.30 [+0.05, −0.05]",0.300,0.05,0.05,"10.96 [+5.47, −5.47]b",10.96,Cluster
4,Engle_2023,2023,Table 2,M37,M37,M0–2V,"0.52 [+0.06, −0.06]",0.520,0.06,0.06,"13.15 [+5.24, −5.24]a",13.15,Cluster
5,Engle_2023,2023,Table 2,Praesepe/Hyades,Praesepe/Hyades,M0–2V,"0.73 [+0.12, −0.12]",0.730,0.12,0.12,"16.06 [+2.91, −12.2]c",16.06,Cluster
6,Engle_2023,2023,Table 2,NGC 6811,NGC 6811,M0–2V,"0.89 [+0.15, −0.15]",0.890,0.15,0.15,"14.19 [+1.45, −1.45]d",14.19,Cluster
7,Engle_2023,2023,Table 2,NGC 752,NGC 752,M0–2V,"1.46 [+0.18, −0.18]",1.460,0.18,0.18,"18.6 [+4.2, −4.2]e",18.60,Cluster
8,Engle_2023,2023,Table 2,L266-195,L266-195,M1V,"2.50 [+1.82, −0.93]",2.500,0.93,1.82,"23.19 [+1.84, −1.84]",23.19,WD comp (L266-196)
9,Engle_2023,2023,Table 2,LP 856-54,LP 856-54,M1–1.5V,"2.52 [+1.58, −0.61]",2.520,0.61,1.58,"23.27 [+0.04, −0.04]",23.27,WD comp (LP 856-53)
10,Engle_2023,2023,Table 2,Ruprecht 147,Ruprecht 147,M0–2V,"2.6 [+0.4, −0.4]",2.600,0.40,0.40,"22.4 [+2.9, −2.9]f,g",22.40,Cluster
11,Engle_2023,2023,Table 2,G59-39,G59-39,M0V,"3.20 [+1.96, −0.93]",3.200,0.93,1.96,"33.82 [+0.07, −0.07]",33.82,WD comp (EGGR 92)
12,Engle_2023,2023,Table 2,LP 775-52,LP 775-52,M0–1V,"3.39 [+0.29, −0.20]",3.390,0.20,0.29,"36.90 [+0.10, −0.10]",36.90,WD comp (LP 775-53)
13,Engle_2023,2023,Table 2,GJ 2131 A,GJ 2131 A,M1V,"3.47 [+1.69, −1.69]",3.470,1.69,1.69,"34.82 [+0.10, −0.10]",34.82,WD comp (GJ 2131 B)
14,Engle_2023,2023,Table 2,G111-72,G111-72,M1.5–2V,"3.64 [+1.35, −0.68]",3.640,0.68,1.35,"38.96 [+0.13, −0.13]",38.96,WD comp (G111-71)
15,Engle_2023,2023,Table 2,HIP 43232 B,HIP 43232 B,M1.5V,"3.95 [+0.35, −0.35]h",3.950,0.35,0.35,"41.3 [+4.1, −4.1]h",41.30,MS comp (HIP 43232 A)
16,Engle_2023,2023,Table 2,M67,M67,M0–2V,"4.0 [+1.0, −0.5]",4.000,0.50,1.00,"31.8 [+3.3, −3.3]i",31.80,Cluster
17,Engle_2023,2023,Table 2,LP 587-54,LP 587-54,M1.5–2V,"6.34 [+1.49, −1.38]",6.340,1.38,1.49,"59.5 [+1.4, −1.4]",59.50,WD comp (LP 587-53)
18,Engle_2023,2023,Table 2,GJ 366,GJ 366,M1.5V,"9.5 [+1.5, −1.5]",9.500,1.50,1.50,"87.1 [+1.2, −1.2]",87.10,Thick disk/halo population
19,Engle_2023,2023,Table 2,GJ 328,GJ 328,M0V,"9.5 [+1.5, −1.5]",9.500,1.50,1.50,"80.5 [+0.6, −0.6]",80.50,Thick disk/halo population

In [15]:
engle_clean.drop(columns=['prot_days_raw', 'age_gyr_raw'], inplace=True, errors='ignore')

In [18]:
engle_clean.drop(columns=['pdf_file', 'source_year', 'sample_group', 'activity_type'], inplace=True, errors='ignore')

In [20]:
engle_clean.columns

Index(['source_paper', 'table_id', 'star_name', 'normalized_name', 'sp_type',
       'age_gyr', 'age_gyr_err_plus', 'age_gyr_err_minus', 'age_note_ref',
       'prot_days', 'prot_err_plus', 'prot_err_minus', 'prot_note_ref',
       'prot_src', 'age_determined_via', 'log_age_gyr_raw', 'log_age_gyr',
       'log_age_unc_raw', 'log_age_unc', 'log_Lx_raw', 'log_Lx',
       'log_Lx_unc_raw', 'log_Lx_unc', 'log_Lx_over_Lbol_raw',
       'log_Lx_over_Lbol', 'log_Lx_over_Lbol_unc_raw', 'log_Lx_over_Lbol_unc',
       'log_Llya_over_Lbol_raw', 'log_Llya_over_Lbol',
       'log_Llya_over_Lbol_unc_raw', 'log_Llya_over_Lbol_unc', 'log_RHK_raw',
       'log_RHK', 'log_RHK_unc_raw', 'log_RHK_unc', 'measurement_src',
       'age_err_hi_gyr', 'age_err_lo_gyr'],
      dtype='object')

In [21]:
activity_cols = [
    "activity_type",
    "log_age_gyr_raw",
    "log_age_gyr",
    "log_age_unc_raw",
    "log_age_unc",
    "log_Lx_raw",
    "log_Lx",
    "log_Lx_unc_raw",
    "log_Lx_unc",
    "log_Lx_over_Lbol_raw",
    "log_Lx_over_Lbol",
    "log_Lx_over_Lbol_unc_raw",
    "log_Lx_over_Lbol_unc",
    "log_Llya_over_Lbol_raw",
    "log_Llya_over_Lbol",
    "log_Llya_over_Lbol_unc_raw",
    "log_Llya_over_Lbol_unc",
    "log_RHK_raw",
    "log_RHK",
    "log_RHK_unc_raw",
    "log_RHK_unc",
    "measurement_src",
]

engle_clean = engle_clean.drop(columns=[c for c in activity_cols if c in engle_clean.columns])

In [23]:
engle_clean = engle_clean.drop(columns=["sp_type", "table_id"])

In [30]:
engle_clean= engle_clean.drop(columns=["age_determined_via"])

In [32]:
engle_clean.to_csv("cf_data/engle_cleaned.csv", index=False)