In [5]:
from pathlib import Path
import pandas as pd

CF_DATA = Path("cf_data")   # change if needed
engle_path = CF_DATA / "engle_clean_star_rows_only.csv"

df = pd.read_csv(engle_path)
print(df.shape)
df.head()

(380, 7)

,source_paper,star_name,normalized_name,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days
0,Engle_2023,L266-195,L266-195,2.50,0.93,1.82,23.19
1,Engle_2023,LP 856-54,LP 856-54,2.52,0.61,1.58,23.27
2,Engle_2023,G59-39,G59-39,3.20,0.93,1.96,33.82
3,Engle_2023,LP 775-52,LP 775-52,3.39,0.20,0.29,36.90
4,Engle_2023,GJ 2131 A,GJ 2131 A,3.47,1.69,1.69,34.82

In [1]:
import re
import pandas as pd

def prep_name(name: str) -> str:
    if pd.isna(name):
        return ""
    s = str(name).strip()

    # normalize whitespace
    s = re.sub(r"\s+", " ", s)

    # optional: keep A/B labels, since they matter
    # just return as-is for now
    return s

df["query_name"] = df["star_name"].apply(prep_name)

NameError: name 'df' is not defined

In [7]:
%pip install astroquery astropy

Requirement already satisfied: astroquery in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.4.11)
Requirement already satisfied: astropy in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.2.0)
Requirement already satisfied: numpy>=1.20 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (2.3.5)
Requirement already satisfied: requests>=2.19 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (2.32.5)
Requirement already satisfied: beautifulsoup4>=4.8 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (4.14.3)
Requirement already satisfied: html5lib>=0.999 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (1.1)
Requirement already satisfied: keyring>=15.0 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (25.7.0)
Requirement already satisfied: pyvo>=1.5 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astroquery) (1.8.1)
Requirement already satisfied: pyerfa>=2.0.1.1 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astropy) (2.0.1.5)
Requirement already satisfied: astropy-iers-data>=0.2025.10.27.0.39.10 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astropy) (0.2026.3.9.0.47.45)
Requirement already satisfied: PyYAML>=6.0.0 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astropy) (6.0.3)
Requirement already satisfied: packaging>=22.0.0 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from astropy) (25.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.8->astroquery) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.8->astroquery) (4.15.0)
Requirement already satisfied: six>=1.9 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from html5lib>=0.999->astroquery) (1.17.0)
Requirement already satisfied: webencodings in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from html5lib>=0.999->astroquery) (0.5.1)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keyring>=15.0->astroquery) (0.2.3)
Requirement already satisfied: jaraco.classes in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keyring>=15.0->astroquery) (3.4.0)
Requirement already satisfied: jaraco.functools in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keyring>=15.0->astroquery) (4.4.0)
Requirement already satisfied: jaraco.context in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keyring>=15.0->astroquery) (6.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19->astroquery) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19->astroquery) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19->astroquery) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.19->astroquery) (2025.11.12)
Requirement already satisfied: more-itertools in c:\Users\caram\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jaraco.classes->keyring>=15.0->astroquery) (10.8.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
from astroquery.simbad import Simbad
import pandas as pd

custom_simbad = Simbad()
custom_simbad.add_votable_fields("ra(d)", "dec(d)", "ids")

def simbad_lookup(name):
    try:
        res = custom_simbad.query_object(name)
        if res is None or len(res) == 0:
            return {
                "simbad_found": False,
                "simbad_main_id": None,
                "simbad_ra_deg": None,
                "simbad_dec_deg": None,
                "simbad_ids": None,
            }

        row = res[0]
        ids = row["IDS"] if "IDS" in row.colnames else None

        return {
            "simbad_found": True,
            "simbad_main_id": str(row["MAIN_ID"]).strip(),
            "simbad_ra_deg": float(row["RA_d"]),
            "simbad_dec_deg": float(row["DEC_d"]),
            "simbad_ids": str(ids) if ids is not None else None,
        }
    except Exception as e:
        return {
            "simbad_found": False,
            "simbad_main_id": None,
            "simbad_ra_deg": None,
            "simbad_dec_deg": None,
            "simbad_ids": None,
            "simbad_error": str(e),
        }

C:\Users\caram\AppData\Local\Temp\ipykernel_42332\4203776614.py:5: DeprecationWarning: 'ra(d)' has been renamed 'ra'. You'll see it appearing with its new name in the output table
  custom_simbad.add_votable_fields("ra(d)", "dec(d)", "ids")
C:\Users\caram\AppData\Local\Temp\ipykernel_42332\4203776614.py:5: DeprecationWarning: 'dec(d)' has been renamed 'dec'. You'll see it appearing with its new name in the output table
  custom_simbad.add_votable_fields("ra(d)", "dec(d)", "ids")

In [9]:
test = df.head(20).copy()
simbad_rows = test["query_name"].apply(simbad_lookup).apply(pd.Series)
test = pd.concat([test, simbad_rows], axis=1)
test[["star_name", "simbad_found", "simbad_main_id", "simbad_ra_deg", "simbad_dec_deg"]]

WARNING: NoResultsWarning: The request executed correctly, but there was no data corresponding to these criteria in SIMBAD [astroquery.simbad.core]

          star_name  simbad_found simbad_main_id simbad_ra_deg simbad_dec_deg
0          L266-195         False           None          None           None
1         LP 856-54         False           None          None           None
2            G59-39         False           None          None           None
3         LP 775-52         False           None          None           None
4         GJ 2131 A         False           None          None           None
5           G111-72         False           None          None           None
6       HIP 43232 B         False           None          None           None
7         LP 587-54         False           None          None           None
8            GJ 366         False           None          None           None
9            GJ 328         False           None          None           None
10           GJ 821         False           None          None           None
11        LP 552-48         False           None          None           None
12          LHS 343         False           None          None           None
13          LHS 173         False           None          None           None
14          LHS 174         False           None          None           None
15        NSV 11919         False           None          None           None
16  Gaia DR3 75525a         False           None          None           None
17           G148-6         False           None          None           None
18         LP 783-2         False           None          None           None
19           G130-6         False           None          None           None

In [10]:
import re

def extract_gaia_dr3_id(ids_str):
    if not isinstance(ids_str, str):
        return None

    m = re.search(r"Gaia DR3\s+(\d+)", ids_str)
    if m:
        return m.group(1)

    return None

In [12]:
test["gaia_dr3_source_id_from_simbad"] = test["simbad_ids"].apply(extract_gaia_dr3_id)

test

,source_paper,star_name,normalized_name,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days,query_name,simbad_found,simbad_main_id,simbad_ra_deg,simbad_dec_deg,simbad_ids,simbad_error,gaia_dr3_source_id_from_simbad
0,Engle_2023,L266-195,L266-195,2.50,0.93,1.82,23.19,L266-195,False,None,None,None,None,'MAIN_ID',None
1,Engle_2023,LP 856-54,LP 856-54,2.52,0.61,1.58,23.27,LP 856-54,False,None,None,None,None,'MAIN_ID',None
2,Engle_2023,G59-39,G59-39,3.20,0.93,1.96,33.82,G59-39,False,None,None,None,None,'MAIN_ID',None
3,Engle_2023,LP 775-52,LP 775-52,3.39,0.20,0.29,36.90,LP 775-52,False,None,None,None,None,'MAIN_ID',None
4,Engle_2023,GJ 2131 A,GJ 2131 A,3.47,1.69,1.69,34.82,GJ 2131 A,False,None,None,None,None,'MAIN_ID',None
5,Engle_2023,G111-72,G111-72,3.64,0.68,1.35,38.96,G111-72,False,None,None,None,None,'MAIN_ID',None
6,Engle_2023,HIP 43232 B,HIP 43232 B,3.95,0.35,0.35,41.30,HIP 43232 B,False,None,None,None,None,'MAIN_ID',None
7,Engle_2023,LP 587-54,LP 587-54,6.34,1.38,1.49,59.50,LP 587-54,False,None,None,None,None,'MAIN_ID',None
8,Engle_2023,GJ 366,GJ 366,9.50,1.50,1.50,87.10,GJ 366,False,None,None,None,None,'MAIN_ID',None
9,Engle_2023,GJ 328,GJ 328,9.50,1.50,1.50,80.50,GJ 328,False,None,None,None,None,'MAIN_ID',None
10,Engle_2023,GJ 821,GJ 821,9.50,1.50,1.50,86.20,GJ 821,False,None,None,None,None,'MAIN_ID',None
11,Engle_2023,LP 552-48,LP 552-48,9.88,2.06,1.78,83.20,LP 552-48,False,None,None,None,None,'MAIN_ID',None
12,Engle_2023,LHS 343,LHS 343,11.50,1.50,1.00,89.20,LHS 343,False,None,None,None,None,'MAIN_ID',None
13,Engle_2023,LHS 173,LHS 173,11.50,1.50,1.00,85.30,LHS 173,False,None,None,None,None,'MAIN_ID',None
14,Engle_2023,LHS 174,LHS 174,11.50,1.50,1.00,90.40,LHS 174,False,None,None,None,None,'MAIN_ID',None
15,Engle_2023,NSV 11919,NSV 11919,1.97,0.35,0.98,21.07,NSV 11919,False,None,None,None,None,'MAIN_ID',None
16,Engle_2023,Gaia DR3 75525a,Gaia DR3 75525a,1.98,0.39,1.01,20.60,Gaia DR3 75525a,False,None,None,None,None,NaN,None
17,Engle_2023,G148-6,G148-6,2.20,0.57,1.35,22.70,G148-6,False,None,None,None,None,'MAIN_ID',None
18,Engle_2023,LP 783-2,LP 783-2,3.12,0.56,1.73,25.45,LP 783-2,False,None,None,None,None,'MAIN_ID',None
19,Engle_2023,G130-6,G130-6,3.60,1.73,1.84,49.50,G130-6,False,None,None,None,None,'MAIN_ID',None

In [13]:
from astroquery.gaia import Gaia

def gaia_from_source_id(source_id):
    if source_id is None or pd.isna(source_id):
        return None

    query = f"""
    SELECT
        gs.source_id,
        gs.ra,
        gs.dec,
        gs.parallax,
        gs.parallax_error,
        gs.pmra,
        gs.pmdec,
        gs.phot_g_mean_mag,
        gs.phot_bp_mean_mag,
        gs.phot_rp_mean_mag,
        gs.bp_rp,
        gs.g_rp,
        gs.ruwe,
        ap.ebpminrp_gspphot
    FROM gaiadr3.gaia_source AS gs
    LEFT JOIN gaiadr3.astrophysical_parameters AS ap
      ON gs.source_id = ap.source_id
    WHERE gs.source_id = {source_id}
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    if len(r) == 0:
        return None
    return r.to_pandas().iloc[0].to_dict()

The archive is unstable and may perform below expectations. If launching multiple, consecutive, heavy queries through Python, please space them out (e.g., using sleep(1)) to avoid overloading the system. Please contact the Gaia helpdesk in case of questions (https://www.cosmos.esa.int/web/gaia/gaia-helpdesk). Workaround solutions for the issues following the December 2025 infrastructure upgrade: https://www.cosmos.esa.int/web/gaia/news#WorkaroundArchive

In [ ]:
from astropy.coordinates import SkyCoord
import astropy.units as u

def gaia_cone_search(ra_deg, dec_deg, radius_arcsec=5):
    if pd.isna(ra_deg) or pd.isna(dec_deg):
        return None

    coord = SkyCoord(ra=ra_deg * u.deg, dec=dec_deg * u.deg, frame="icrs")
    radius = u.Quantity(radius_arcsec, u.arcsec)

    query = f"""
    SELECT TOP 10
        gs.source_id,
        gs.ra,
        gs.dec,
        gs.parallax,
        gs.parallax_error,
        gs.pmra,
        gs.pmdec,
        gs.phot_g_mean_mag,
        gs.phot_bp_mean_mag,
        gs.phot_rp_mean_mag,
        gs.bp_rp,
        gs.g_rp,
        gs.ruwe,
        ap.ebpminrp_gspphot,
        DISTANCE(
            POINT('ICRS', gs.ra, gs.dec),
            POINT('ICRS', {ra_deg}, {dec_deg})
        ) * 3600.0 AS dist_arcsec
    FROM gaiadr3.gaia_source AS gs
    LEFT JOIN gaiadr3.astrophysical_parameters AS ap
      ON gs.source_id = ap.source_id
    WHERE 1 = CONTAINS(
        POINT('ICRS', gs.ra, gs.dec),
        CIRCLE('ICRS', {ra_deg}, {dec_deg}, {radius.to(u.deg).value})
    )
    ORDER BY dist_arcsec ASC
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    if len(r) == 0:
        return None
    return r.to_pandas()

In [ ]:
def choose_best_gaia_match(candidates):
    if candidates is None or len(candidates) == 0:
        return None, "no_gaia_match"

    best = candidates.sort_values("dist_arcsec").iloc[0].to_dict()

    n_close = (candidates["dist_arcsec"] <= 2.0).sum()
    flags = []

    if n_close > 1:
        flags.append("multiple_close_matches")
    if pd.notna(best.get("ruwe")) and best["ruwe"] >= 1.2:
        flags.append("high_ruwe")
    if pd.isna(best.get("ebpminrp_gspphot")):
        flags.append("missing_reddening")

    flag = ";".join(flags) if flags else "ok"
    return best, flag

In [16]:
def resolve_engle_star(row):
    out = {
        "simbad_main_id": None,
        "simbad_ra_deg": None,
        "simbad_dec_deg": None,
        "gaia_dr3_source_id": None,
        "match_sep_arcsec": None,
        "ra": None,
        "dec": None,
        "parallax": None,
        "pmra": None,
        "pmdec": None,
        "phot_g_mean_mag": None,
        "phot_bp_mean_mag": None,
        "phot_rp_mean_mag": None,
        "bp_rp": None,
        "g_rp": None,
        "ruwe": None,
        "ebpminrp_gspphot": None,
        "bp_rp_0": None,
        "match_flag": None,
    }

    sim = simbad_lookup(row["query_name"])
    out["simbad_main_id"] = sim.get("simbad_main_id")
    out["simbad_ra_deg"] = sim.get("simbad_ra_deg")
    out["simbad_dec_deg"] = sim.get("simbad_dec_deg")

    gaia_id = extract_gaia_dr3_id(sim.get("simbad_ids"))
    if gaia_id is not None:
        g = gaia_from_source_id(gaia_id)
        if g is not None:
            out["gaia_dr3_source_id"] = g.get("source_id")
            out["ra"] = g.get("ra")
            out["dec"] = g.get("dec")
            out["parallax"] = g.get("parallax")
            out["pmra"] = g.get("pmra")
            out["pmdec"] = g.get("pmdec")
            out["phot_g_mean_mag"] = g.get("phot_g_mean_mag")
            out["phot_bp_mean_mag"] = g.get("phot_bp_mean_mag")
            out["phot_rp_mean_mag"] = g.get("phot_rp_mean_mag")
            out["bp_rp"] = g.get("bp_rp")
            out["g_rp"] = g.get("g_rp")
            out["ruwe"] = g.get("ruwe")
            out["ebpminrp_gspphot"] = g.get("ebpminrp_gspphot")
            if pd.notna(out["bp_rp"]) and pd.notna(out["ebpminrp_gspphot"]):
                out["bp_rp_0"] = out["bp_rp"] - out["ebpminrp_gspphot"]
            out["match_flag"] = "matched_via_simbad_gaia_id"
            return pd.Series(out)

    candidates = gaia_cone_search(sim.get("simbad_ra_deg"), sim.get("simbad_dec_deg"), radius_arcsec=5)
    best, flag = choose_best_gaia_match(candidates)

    if best is None:
        out["match_flag"] = flag
        return pd.Series(out)

    out["gaia_dr3_source_id"] = best.get("source_id")
    out["match_sep_arcsec"] = best.get("dist_arcsec")
    out["ra"] = best.get("ra")
    out["dec"] = best.get("dec")
    out["parallax"] = best.get("parallax")
    out["pmra"] = best.get("pmra")
    out["pmdec"] = best.get("pmdec")
    out["phot_g_mean_mag"] = best.get("phot_g_mean_mag")
    out["phot_bp_mean_mag"] = best.get("phot_bp_mean_mag")
    out["phot_rp_mean_mag"] = best.get("phot_rp_mean_mag")
    out["bp_rp"] = best.get("bp_rp")
    out["g_rp"] = best.get("g_rp")
    out["ruwe"] = best.get("ruwe")
    out["ebpminrp_gspphot"] = best.get("ebpminrp_gspphot")

    if pd.notna(out["bp_rp"]) and pd.notna(out["ebpminrp_gspphot"]):
        out["bp_rp_0"] = out["bp_rp"] - out["ebpminrp_gspphot"]

    out["match_flag"] = flag
    return pd.Series(out)

In [17]:
sample = df.head(25).copy()
resolved = sample.apply(resolve_engle_star, axis=1)
sample_out = pd.concat([sample, resolved], axis=1)

sample_out[[
    "star_name",
    "simbad_main_id",
    "gaia_dr3_source_id",
    "match_sep_arcsec",
    "bp_rp",
    "g_rp",
    "ebpminrp_gspphot",
    "bp_rp_0",
    "ruwe",
    "match_flag",
]]

WARNING: NoResultsWarning: The request executed correctly, but there was no data corresponding to these criteria in SIMBAD [astroquery.simbad.core]

,star_name,simbad_main_id,gaia_dr3_source_id,match_sep_arcsec,bp_rp,g_rp,ebpminrp_gspphot,bp_rp_0,ruwe,match_flag
0,L266-195,None,None,None,None,None,None,None,None,no_gaia_match
1,LP 856-54,None,None,None,None,None,None,None,None,no_gaia_match
2,G59-39,None,None,None,None,None,None,None,None,no_gaia_match
3,LP 775-52,None,None,None,None,None,None,None,None,no_gaia_match
4,GJ 2131 A,None,None,None,None,None,None,None,None,no_gaia_match
5,G111-72,None,None,None,None,None,None,None,None,no_gaia_match
6,HIP 43232 B,None,None,None,None,None,None,None,None,no_gaia_match
7,LP 587-54,None,None,None,None,None,None,None,None,no_gaia_match
8,GJ 366,None,None,None,None,None,None,None,None,no_gaia_match
9,GJ 328,None,None,None,None,None,None,None,None,no_gaia_match
10,GJ 821,None,None,None,None,None,None,None,None,no_gaia_match
11,LP 552-48,None,None,None,None,None,None,None,None,no_gaia_match
12,LHS 343,None,None,None,None,None,None,None,None,no_gaia_match
13,LHS 173,None,None,None,None,None,None,None,None,no_gaia_match
14,LHS 174,None,None,None,None,None,None,None,None,no_gaia_match
15,NSV 11919,None,None,None,None,None,None,None,None,no_gaia_match
16,Gaia DR3 75525a,None,None,None,None,None,None,None,None,no_gaia_match
17,G148-6,None,None,None,None,None,None,None,None,no_gaia_match
18,LP 783-2,None,None,None,None,None,None,None,None,no_gaia_match
19,G130-6,None,None,None,None,None,None,None,None,no_gaia_match
20,LP 498-25,None,None,None,None,None,None,None,None,no_gaia_match
21,LHS 353,None,None,None,None,None,None,None,None,no_gaia_match
22,LP 906-23,None,None,None,None,None,None,None,None,no_gaia_match
23,40 Eri C,None,None,None,None,None,None,None,None,no_gaia_match
24,G201-40,None,None,None,None,None,None,None,None,no_gaia_match

In [18]:
from astroquery.simbad import Simbad

s = Simbad()
s.add_votable_fields("ra(d)", "dec(d)", "ids")

res = s.query_object("GJ 366")
print(res)

C:\Users\caram\AppData\Local\Temp\ipykernel_42332\1904562137.py:4: DeprecationWarning: 'ra(d)' has been renamed 'ra'. You'll see it appearing with its new name in the output table
  s.add_votable_fields("ra(d)", "dec(d)", "ids")
C:\Users\caram\AppData\Local\Temp\ipykernel_42332\1904562137.py:4: DeprecationWarning: 'dec(d)' has been renamed 'dec'. You'll see it appearing with its new name in the output table
  s.add_votable_fields("ra(d)", "dec(d)", "ids")

  main_id           ra        ... matched_id
                   deg        ...
----------- ----------------- ... ----------
BD+76  3952 146.7020252337433 ...     GJ 366

In [20]:
from astroquery.simbad import Simbad

s = Simbad()
s.add_votable_fields("ra(d)", "dec(d)", "ids")

res = s.query_object("GJ 366")
print(res.colnames)
print(res[0])

C:\Users\caram\AppData\Local\Temp\ipykernel_42332\359297842.py:4: DeprecationWarning: 'ra(d)' has been renamed 'ra'. You'll see it appearing with its new name in the output table
  s.add_votable_fields("ra(d)", "dec(d)", "ids")
C:\Users\caram\AppData\Local\Temp\ipykernel_42332\359297842.py:4: DeprecationWarning: 'dec(d)' has been renamed 'dec'. You'll see it appearing with its new name in the output table
  s.add_votable_fields("ra(d)", "dec(d)", "ids")

['main_id', 'ra', 'dec', 'coo_err_maj', 'coo_err_min', 'coo_err_angle', 'coo_wavelength', 'coo_bibcode', 'ids', 'matched_id']
  main_id           ra               dec        coo_err_maj coo_err_min coo_err_angle coo_wavelength     coo_bibcode                                                                                                                                                                                                                                                                                  ids                                                                                                                                                                                                                                                                              matched_id
                   deg               deg            mas         mas          deg
----------- ----------------- ----------------- ----------- ----------- ------------- -------------- ------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----------
BD+76  3952 146.7020252337433 76.04391682018667      0.0111      0.0119            90              O 2020yCat.1350....0G TIC 219431676|Karmn J09468+760|GJ 366|HIP 47981|Gaia DR3 1130450270073924608|CNS5 2420|PLX 2302|LSPM J0946+7602|ASCC   30041|AC +76  3952|AC +76  3952-0|CSI+76-09423|CSI+76-09417|Ci 20  545|G 252-44|G 253-30|GCRV 60845|GEN# +9.80252044|HIC  47981|LFT  679|LHS  2188|LTT 12585|MCC 120|NLTT 22468|PM 09417+7617|Ross  434|TYC 4542-2612-1|VVO 134|[RHG95]  1537|2MASS J09464844+7602388|USNO-B1.0 1660-00055540|PLX 2302.00|BD+76  3952|GCRV  3533 E|UCAC4 831-011894|PM J09468+7602|Gaia DR1 1130450270073924608|WEB  8978|Gaia DR2 1130450270073924608     GJ 366

In [ ]:
from astroquery.simbad import Simbad
import pandas as pd

custom_simbad = Simbad()
custom_simbad.add_votable_fields("ra(d)", "dec(d)", "ids")

def _get_first_existing(row, possible_names):
    for name in possible_names:
        if name in row.colnames:
            val = row[name]
            if val is not None:
                return val
    return None

def simbad_lookup(name):
    if not isinstance(name, str) or not name.strip():
        return {
            "simbad_found": False,
            "simbad_main_id": None,
            "simbad_ra_deg": None,
            "simbad_dec_deg": None,
            "simbad_ids": None,
            "simbad_status": "empty_name",
        }

    try:
        res = custom_simbad.query_object(name)

        if res is None or len(res) == 0:
            return {
                "simbad_found": False,
                "simbad_main_id": None,
                "simbad_ra_deg": None,
                "simbad_dec_deg": None,
                "simbad_ids": None,
                "simbad_status": "no_result",
            }

        row = res[0]

        main_id = _get_first_existing(row, ["MAIN_ID", "main_id"])
        ra_val   = _get_first_existing(row, ["RA_d", "ra", "RA"])
        dec_val  = _get_first_existing(row, ["DEC_d", "dec", "DEC"])
        ids_val  = _get_first_existing(row, ["IDS", "ids"])

        return {
            "simbad_found": True,
            "simbad_main_id": str(main_id).strip() if main_id is not None else None,
            "simbad_ra_deg": float(ra_val) if ra_val is not None else None,
            "simbad_dec_deg": float(dec_val) if dec_val is not None else None,
            "simbad_ids": str(ids_val) if ids_val is not None else None,
            "simbad_status": "ok",
        }

    except Exception as e:
        return {
            "simbad_found": False,
            "simbad_main_id": None,
            "simbad_ra_deg": None,
            "simbad_dec_deg": None,
            "simbad_ids": None,
            "simbad_status": f"error: {e}",
        }

In [22]:
test_names = ["GJ 366", "GJ 821", "HIP 43232 B", "LP 856-54"]

for name in test_names:
    print(name, simbad_lookup(name))

GJ 366 {'simbad_found': True, 'simbad_main_id': 'BD+76  3952', 'simbad_ra_deg': 146.7020252337433, 'simbad_dec_deg': 76.04391682018667, 'simbad_ids': 'TIC 219431676|Karmn J09468+760|GJ 366|HIP 47981|Gaia DR3 1130450270073924608|CNS5 2420|PLX 2302|LSPM J0946+7602|ASCC   30041|AC +76  3952|AC +76  3952-0|CSI+76-09423|CSI+76-09417|Ci 20  545|G 252-44|G 253-30|GCRV 60845|GEN# +9.80252044|HIC  47981|LFT  679|LHS  2188|LTT 12585|MCC 120|NLTT 22468|PM 09417+7617|Ross  434|TYC 4542-2612-1|VVO 134|[RHG95]  1537|2MASS J09464844+7602388|USNO-B1.0 1660-00055540|PLX 2302.00|BD+76  3952|GCRV  3533 E|UCAC4 831-011894|PM J09468+7602|Gaia DR1 1130450270073924608|WEB  8978|Gaia DR2 1130450270073924608', 'simbad_status': 'ok'}
GJ 821 {'simbad_found': True, 'simbad_main_id': 'Wolf  918', 'simbad_ra_deg': 317.32261313117283, 'simbad_dec_deg': -13.3025036466225, 'simbad_ids': 'TIC 214576902|StKM 2-1498|GJ 821|Gaia DR3 6885776098199761024|PLX 5084|CNS5 5223|CSI-13-21065|Ci 20 1261|GEN# +6.10140918|GSC 05783-00134|HIC 104432|HIP 104432|JP11  5194|LFT 1607|LHS    65|LPM 767|LTT  8393|NLTT 50633|PM 21065-1329|TYC 5783-1513-1|VVO 372|Wolf  918|[RHG95]  3307|2MASS J21091740-1318080|PLX 5084.00|UCAC2  27211430|WISEA J210917.93-131830.3|GCRV 26191|UCAC4 384-153409|PM J21092-1318|Gaia DR2 6885776098199761024', 'simbad_status': 'ok'}
HIP 43232 B {'simbad_found': True, 'simbad_main_id': 'UCAC3 222-97968', 'simbad_ra_deg': 132.10383476114959, 'simbad_dec_deg': 20.705234770251387, 'simbad_ids': 'Gaia DR3 661794060190112000|UCAC3 222-97968|UCAC4 554-043601|2MASS J08482492+2042188|SDSS J084824.90+204218.5|PSO J132.1036+20.7050|UGCS J084824.89+204218.5|HIP 43232B', 'simbad_status': 'ok'}
LP 856-54 {'simbad_found': True, 'simbad_main_id': 'L  619-49', 'simbad_ra_deg': 207.84678749431, 'simbad_dec_deg': -27.564566865779998, 'simbad_ids': 'TIC 72511761|Gaia DR3 6177238671977087360|CCDM J13514-2734A|IDS 13457-2704 A|LP  856-54|WDS J13513-2734A|2MASS J13512321-2733519|RAVE J135123.1-273351|USNO-B1.0 0624-00405344|** LDS  855A|WISEA J135123.28-273354.4|PM J13513-2733|UCAC4 313-074611|LTT  5381|Gaia DR2 6177238671977087360|L  619-49|NLTT 35441', 'simbad_status': 'ok'}

In [23]:
tmp = df.head(20).copy()
tmp["query_name"] = tmp["star_name"]

sim = tmp["query_name"].apply(simbad_lookup).apply(pd.Series)
tmp = pd.concat([tmp, sim], axis=1)

tmp[["star_name", "simbad_found", "simbad_main_id", "simbad_ra_deg", "simbad_dec_deg", "simbad_ids", "simbad_status"]]

WARNING: NoResultsWarning: The request executed correctly, but there was no data corresponding to these criteria in SIMBAD [astroquery.simbad.core]

,star_name,simbad_found,simbad_main_id,simbad_ra_deg,simbad_dec_deg,simbad_ids,simbad_status
0,L266-195,True,L 266-195,246.759148,-54.197447,TIC 220978213|Gaia DR3 5932005595773303040|TYC...,ok
1,LP 856-54,True,L 619-49,207.846787,-27.564567,TIC 72511761|Gaia DR3 6177238671977087360|CCDM...,ok
2,G59-39,True,G 59-39,191.805960,14.703900,TIC 92043862|Gaia DR3 3930922058356114432|ASCC...,ok
3,LP 775-52,True,LP 775-52,65.431051,-16.000157,TIC 71011069|Gaia DR3 3175193288128400768|2MAS...,ok
4,GJ 2131 A,True,G 154-B5A,266.472296,-13.306205,TIC 419437827|WISE J174553.39-131821.3|Gaia DR...,ok
5,G111-72,True,G 111-72,125.017625,38.578088,TIC 18783116|Gaia DR3 908364387441657472|AP J0...,ok
6,HIP 43232 B,True,UCAC3 222-97968,132.103835,20.705235,Gaia DR3 661794060190112000|UCAC3 222-97968|UC...,ok
7,LP 587-54,True,G 271-52,20.815330,-2.145895,TIC 248949078|Gaia DR3 2485305370114328576|2MA...,ok
8,GJ 366,True,BD+76 3952,146.702025,76.043917,TIC 219431676|Karmn J09468+760|GJ 366|HIP 4798...,ok
9,GJ 328,True,BD+02 2098,133.781757,1.546504,TIC 265373654|StKM 2-525|HIP 43790|Gaia DR3 57...,ok
10,GJ 821,True,Wolf 918,317.322613,-13.302504,TIC 214576902|StKM 2-1498|GJ 821|Gaia DR3 6885...,ok
11,LP 552-48,True,LP 552-48,170.874325,7.024919,TIC 291065627|StKM 2-729|GJ 9358|HIP 55605|Gai...,ok
12,LHS 343,True,G 61-21,194.098916,15.695720,TIC 88119458|Gaia DR3 3931313793733241088|2MAS...,ok
13,LHS 173,True,Ross 34,52.221421,37.382447,TIC 194856365|AP J03285302+3722579|HIP 16209|G...,ok
14,LHS 174,True,Ross 585,52.686746,34.018664,TIC 90569855|Gaia DR3 220989197096055040|PM J0...,ok
15,NSV 11919,True,L 923-22,290.139411,-7.662153,TIC 3567372|GJ 754.1 B|Gaia DR3 42017816969940...,ok
16,Gaia DR3 75525a,False,None,NaN,NaN,None,no_result
17,G148-6,True,G 148-6,176.483218,31.825258,TIC 82311842|Gaia DR3 4021566209266336640|USNO...,ok
18,LP 783-2,True,LP 783-2,115.080716,-17.412754,TIC 289113766|GJ 283 B|Gaia DR3 57172789118842...,ok
19,G130-6,True,G 130-6,355.971285,32.594098,TIC 288144878|StKM 2-1765|GJ 905.2 A|GJ 9838 A...,ok

In [26]:
import re
import pandas as pd

def extract_gaia_dr3_id(ids_str):
    if not isinstance(ids_str, str) or not ids_str.strip():
        return None

    m = re.search(r"Gaia DR3\s+(\d+)", ids_str)
    if m:
        return m.group(1)

    return None

In [28]:
print(df.columns.tolist())

['source_paper', 'star_name', 'normalized_name', 'age_gyr', 'age_err_lo_gyr', 'age_err_hi_gyr', 'prot_days', 'query_name']

In [29]:
sim = df["query_name"].apply(simbad_lookup).apply(pd.Series)
print(sim.columns.tolist())
sim.head()

WARNING: NoResultsWarning: The request executed correctly, but there was no data corresponding to these criteria in SIMBAD [astroquery.simbad.core]

['simbad_found', 'simbad_main_id', 'simbad_ra_deg', 'simbad_dec_deg', 'simbad_ids', 'simbad_status']

,simbad_found,simbad_main_id,simbad_ra_deg,simbad_dec_deg,simbad_ids,simbad_status
0,True,L 266-195,246.759148,-54.197447,TIC 220978213|Gaia DR3 5932005595773303040|TYC...,ok
1,True,L 619-49,207.846787,-27.564567,TIC 72511761|Gaia DR3 6177238671977087360|CCDM...,ok
2,True,G 59-39,191.805960,14.703900,TIC 92043862|Gaia DR3 3930922058356114432|ASCC...,ok
3,True,LP 775-52,65.431051,-16.000157,TIC 71011069|Gaia DR3 3175193288128400768|2MAS...,ok
4,True,G 154-B5A,266.472296,-13.306205,TIC 419437827|WISE J174553.39-131821.3|Gaia DR...,ok

In [30]:
df = pd.concat([df, sim], axis=1)
print(df.columns.tolist())

['source_paper', 'star_name', 'normalized_name', 'age_gyr', 'age_err_lo_gyr', 'age_err_hi_gyr', 'prot_days', 'query_name', 'simbad_found', 'simbad_main_id', 'simbad_ra_deg', 'simbad_dec_deg', 'simbad_ids', 'simbad_status']

In [31]:
df["gaia_dr3_source_id_from_simbad"] = df["simbad_ids"].apply(extract_gaia_dr3_id)

In [32]:
df[[
    "star_name",
    "simbad_main_id",
    "simbad_ids",
    "gaia_dr3_source_id_from_simbad"
]].head(20)

,star_name,simbad_main_id,simbad_ids,gaia_dr3_source_id_from_simbad
0,L266-195,L 266-195,TIC 220978213|Gaia DR3 5932005595773303040|TYC...,5932005595773303040
1,LP 856-54,L 619-49,TIC 72511761|Gaia DR3 6177238671977087360|CCDM...,6177238671977087360
2,G59-39,G 59-39,TIC 92043862|Gaia DR3 3930922058356114432|ASCC...,3930922058356114432
3,LP 775-52,LP 775-52,TIC 71011069|Gaia DR3 3175193288128400768|2MAS...,3175193288128400768
4,GJ 2131 A,G 154-B5A,TIC 419437827|WISE J174553.39-131821.3|Gaia DR...,4149820284980989184
5,G111-72,G 111-72,TIC 18783116|Gaia DR3 908364387441657472|AP J0...,908364387441657472
6,HIP 43232 B,UCAC3 222-97968,Gaia DR3 661794060190112000|UCAC3 222-97968|UC...,661794060190112000
7,LP 587-54,G 271-52,TIC 248949078|Gaia DR3 2485305370114328576|2MA...,2485305370114328576
8,GJ 366,BD+76 3952,TIC 219431676|Karmn J09468+760|GJ 366|HIP 4798...,1130450270073924608
9,GJ 328,BD+02 2098,TIC 265373654|StKM 2-525|HIP 43790|Gaia DR3 57...,577602496345490176
10,GJ 821,Wolf 918,TIC 214576902|StKM 2-1498|GJ 821|Gaia DR3 6885...,6885776098199761024
11,LP 552-48,LP 552-48,TIC 291065627|StKM 2-729|GJ 9358|HIP 55605|Gai...,3817534337625985280
12,LHS 343,G 61-21,TIC 88119458|Gaia DR3 3931313793733241088|2MAS...,3931313793733241088
13,LHS 173,Ross 34,TIC 194856365|AP J03285302+3722579|HIP 16209|G...,222749343414443648
14,LHS 174,Ross 585,TIC 90569855|Gaia DR3 220989197096055040|PM J0...,220989197096055040
15,NSV 11919,L 923-22,TIC 3567372|GJ 754.1 B|Gaia DR3 42017816969940...,4201781696994082944
16,Gaia DR3 75525a,None,None,None
17,G148-6,G 148-6,TIC 82311842|Gaia DR3 4021566209266336640|USNO...,4021566209266336640
18,LP 783-2,LP 783-2,TIC 289113766|GJ 283 B|Gaia DR3 57172789118842...,5717278911884264576
19,G130-6,G 130-6,TIC 288144878|StKM 2-1765|GJ 905.2 A|GJ 9838 A...,2871730758921709952

In [34]:
import pandas as pd

df = pd.read_csv("cf_data/engle_clean_star_rows_only.csv")
df["query_name"] = df["star_name"].apply(prep_name)
sim = df["query_name"].apply(simbad_lookup).apply(pd.Series)
df = pd.concat([df, sim], axis=1)
df["gaia_dr3_source_id_from_simbad"] = df["simbad_ids"].apply(extract_gaia_dr3_id)

WARNING: NoResultsWarning: The request executed correctly, but there was no data corresponding to these criteria in SIMBAD [astroquery.simbad.core]

In [35]:
df

,source_paper,star_name,normalized_name,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days,query_name,simbad_found,simbad_main_id,simbad_ra_deg,simbad_dec_deg,simbad_ids,simbad_status,gaia_dr3_source_id_from_simbad
0,Engle_2023,L266-195,L266-195,2.50,0.93,1.82,23.19,L266-195,True,L 266-195,246.759148,-54.197447,TIC 220978213|Gaia DR3 5932005595773303040|TYC...,ok,5932005595773303040
1,Engle_2023,LP 856-54,LP 856-54,2.52,0.61,1.58,23.27,LP 856-54,True,L 619-49,207.846787,-27.564567,TIC 72511761|Gaia DR3 6177238671977087360|CCDM...,ok,6177238671977087360
2,Engle_2023,G59-39,G59-39,3.20,0.93,1.96,33.82,G59-39,True,G 59-39,191.805960,14.703900,TIC 92043862|Gaia DR3 3930922058356114432|ASCC...,ok,3930922058356114432
3,Engle_2023,LP 775-52,LP 775-52,3.39,0.20,0.29,36.90,LP 775-52,True,LP 775-52,65.431051,-16.000157,TIC 71011069|Gaia DR3 3175193288128400768|2MAS...,ok,3175193288128400768
4,Engle_2023,GJ 2131 A,GJ 2131 A,3.47,1.69,1.69,34.82,GJ 2131 A,True,G 154-B5A,266.472296,-13.306205,TIC 419437827|WISE J174553.39-131821.3|Gaia DR...,ok,4149820284980989184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Engle_2024,GJ 581,GJ 581,NaN,NaN,NaN,147.80,GJ 581,True,BD-07 4003,229.861779,-7.722275,TIC 36853511|Karmn J15194-077|MCC 159|StKM 2-1...,ok,6322070093095493504
376,Engle_2024,GJ 699,GJ 699,NaN,NaN,NaN,149.50,GJ 699,True,NAME Barnard's star,269.452077,4.693365,TIC 325554331|MCC 799|StKM 2-1355|GJ 699|HIP 8...,ok,4472832130942575872
377,Engle_2024,GJ 273,GJ 273,NaN,NaN,NaN,160.83,GJ 273,True,BD+05 1668,111.852079,5.225789,AP J07272450+0513329|MCC 17|GJ 273|HIP 36208|G...,ok,3139847906307949696
378,Engle_2024,LP 855-60,LP 855-60,NaN,NaN,NaN,154.89,LP 855-60,True,LP 855-60,206.087105,-26.309772,TIC 101824432|Gaia DR3 6190352001701947520|CNS...,ok,6190352001701947520
379,Engle_2024,GJ 191,GJ 191,NaN,NaN,NaN,153.20,GJ 191,True,HD 33793,77.919124,-45.018434,TIC 200385493|GJ 191|HIP 24186|Gaia DR3 481059...,ok,4810594479418041856

In [ ]:
import re

def extract_gaia_dr3_id(ids_str):
    if not isinstance(ids_str, str) or not ids_str.strip():
        return None

    m = re.search(r"Gaia DR3\s+(\d+)", ids_str)
    if m:
        return m.group(1)

    return None

In [37]:
df["gaia_dr3_source_id_from_simbad"] = df["simbad_ids"].apply(extract_gaia_dr3_id)

In [38]:
df[[
    "star_name",
    "simbad_main_id",
    "gaia_dr3_source_id_from_simbad"
]].head(20)

          star_name   simbad_main_id gaia_dr3_source_id_from_simbad
0          L266-195       L  266-195            5932005595773303040
1         LP 856-54        L  619-49            6177238671977087360
2            G59-39         G  59-39            3930922058356114432
3         LP 775-52       LP  775-52            3175193288128400768
4         GJ 2131 A        G 154-B5A            4149820284980989184
5           G111-72         G 111-72             908364387441657472
6       HIP 43232 B  UCAC3 222-97968             661794060190112000
7         LP 587-54         G 271-52            2485305370114328576
8            GJ 366      BD+76  3952            1130450270073924608
9            GJ 328      BD+02  2098             577602496345490176
10           GJ 821        Wolf  918            6885776098199761024
11        LP 552-48       LP  552-48            3817534337625985280
12          LHS 343         G  61-21            3931313793733241088
13          LHS 173        Ross   34             222749343414443648
14          LHS 174        Ross  585             220989197096055040
15        NSV 11919        L  923-22            4201781696994082944
16  Gaia DR3 75525a             None                           None
17           G148-6          G 148-6            4021566209266336640
18         LP 783-2        LP  783-2            5717278911884264576
19           G130-6          G 130-6            2871730758921709952

In [39]:
df["gaia_dr3_source_id_from_simbad"].notna().sum(), len(df)

(np.int64(329), 380)

In [40]:
matched_direct = df[df["gaia_dr3_source_id_from_simbad"].notna()].copy()
needs_cone = df[df["gaia_dr3_source_id_from_simbad"].isna()].copy()

In [41]:
direct_ids = (
    matched_direct["gaia_dr3_source_id_from_simbad"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

len(direct_ids)

261

In [42]:
from astroquery.gaia import Gaia
import pandas as pd

def chunk_list(lst, n=200):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]

def query_gaia_by_source_ids(source_ids):
    ids_str = ",".join(source_ids)

    query = f"""
    SELECT
        gs.source_id,
        gs.ra,
        gs.dec,
        gs.parallax,
        gs.parallax_error,
        gs.pmra,
        gs.pmdec,
        gs.phot_g_mean_mag,
        gs.phot_bp_mean_mag,
        gs.phot_rp_mean_mag,
        gs.bp_rp,
        gs.g_rp,
        gs.ruwe,
        ap.ebpminrp_gspphot
    FROM gaiadr3.gaia_source AS gs
    LEFT JOIN gaiadr3.astrophysical_parameters AS ap
      ON gs.source_id = ap.source_id
    WHERE gs.source_id IN ({ids_str})
    """

    job = Gaia.launch_job(query)
    r = job.get_results()
    return r.to_pandas()

In [43]:
gaia_parts = []

for chunk in chunk_list(direct_ids, n=200):
    part = query_gaia_by_source_ids(chunk)
    gaia_parts.append(part)

gaia_direct = pd.concat(gaia_parts, ignore_index=True)
gaia_direct.head()

HTTPError: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         gs.source_id,
        gs.ra,
        gs.dec,
        gs.parallax,
        gs.parallax_error,
        gs.pmra,
        gs.pmdec,
        gs.phot_g_mean_mag,
        gs.phot_bp_mean_mag,
        gs.phot_rp_mean_mag,
        gs.bp_rp,
        gs.g_rp,
        gs.ruwe,
        ap.ebpminrp_gspphot
    FROM gaiadr3.gaia_source AS gs
    LEFT JOIN gaiadr3.astrophysical_parameters AS ap
      ON gs.source_id = ap.source_id
    WHERE gs.source_id IN (2783324526489670144,170639948323693952,4540061704989418240,3855208897392952192,1803475188714186368,1254695603704323712,2828928008202069376,3089711447388931584,5925209583053212800,5144740907820131840,1229089524081628416,266846631637524864,778947814402602752,1472718211053416320,4364480521350598144,1503625448550796032,3657653114880309248,459661938487952000,3741297293732404352,5075098253634738176,2461728194387221504,6887195533352079616,3530383784971799680,2538451703458011264,3136952686035250688,3492638237986110080,2461635667907177472,2595284016771502080,2507016253701863040,5401688460176652544,4505805591300126080,6321908842843721088,4574048021719710848,6078114541943893888,1071195187567668480,6327575515318207104,5425628298649940608,6285080838309725440,4893118771316702720,3571124882669324800,2384348242516852864,6378584028690858496,5571142580908768384,6021430250773348736,5217602588456509696,6882963066420161664,772430527947893632,5815970800722940800,2768048564768256512,4689958778035794048,4192723988912416256,4672462936698379520,5985290231327158144,6814962601568904576,2918040883015489408,5686163724944033792,3179036008830848,6044721476534419584,5329084752471816192,6469383588698276480,6190352001701947520)
    ' for job '216f990a-3242-11f1-9054-bc97e148b76b-O': 16 unresolved identifiers: gaia_source [l.17 c.10 - l.17 c.29], source_id [l.3 c.19 - l.3 c.31], ra [l.4 c.9 - l.4 c.14], dec [l.5 c.9 - l.5 c.15], parallax [l.6 c.9 - l.6 c.20], parallax_error [l.7 c.9 - l.7 c.26], pmra [l.8 c.9 - l.8 c.16], pmdec [l.9 c.9 - l.9 c.17], phot_g_mean_mag [l.10 c.9 - l.10 c.27], phot_bp_mean_mag [l.11 c.9 - l.11 c.28], phot_rp_mean_mag [l.12 c.9 - l.12 c.28], bp_rp [l.13 c.9 - l.13 c.17], g_rp [l.14 c.9 - l.14 c.16], ruwe [l.15 c.9 - l.15 c.16], source_id [l.19 c.10 - l.19 c.22], source_id [l.20 c.11 - l.20 c.23] !
 - Unknown table "gaiadr3.gaia_source" (alias gs) !
 - Unknown column "gs.source_id" !
 - Unknown column "gs.ra" !
 - Unknown column "gs.dec" !
 - Unknown column "gs.parallax" !
 - Unknown column "gs.parallax_error" !
 - Unknown column "gs.pmra" !
 - Unknown column "gs.pmdec" !
 - Unknown column "gs.phot_g_mean_mag" !
 - Unknown column "gs.phot_bp_mean_mag" !
 - Unknown column "gs.phot_rp_mean_mag" !
 - Unknown column "gs.bp_rp" !
 - Unknown column "gs.g_rp" !
 - Unknown column "gs.ruwe" !
 - Unknown column "gs.source_id" !
 - Unknown column "gs.source_id" !

In [44]:
from astroquery.gaia import Gaia
import pandas as pd

def query_gaia_by_source_ids(source_ids):
    ids_str = ",".join(source_ids)

    query = f"""
    SELECT
        source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id IN ({ids_str})
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    return r.to_pandas()

In [45]:
def query_astrophysical_by_source_ids(source_ids):
    ids_str = ",".join(source_ids)

    query = f"""
    SELECT
        source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id IN ({ids_str})
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    return r.to_pandas()

In [46]:
gaia_parts = []
ap_parts = []

for chunk in chunk_list(direct_ids, n=200):
    gaia_parts.append(query_gaia_by_source_ids(chunk))
    ap_parts.append(query_astrophysical_by_source_ids(chunk))

gaia_core = pd.concat(gaia_parts, ignore_index=True)
gaia_ap = pd.concat(ap_parts, ignore_index=True)

HTTPError: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id IN (5932005595773303040,6177238671977087360,3930922058356114432,3175193288128400768,4149820284980989184,908364387441657472,661794060190112000,2485305370114328576,1130450270073924608,577602496345490176,6885776098199761024,3817534337625985280,3931313793733241088,222749343414443648,220989197096055040,4201781696994082944,4021566209266336640,5717278911884264576,2871730758921709952,3738752852026813184,3630015546177181952,5402903764121955840,3195919254111314816,1600882199829338368,5853498713190525696,946030529073022080,1996725077535282944,1379500928055726848,975968718869126144,3098328182579892096,3340477717172813568,67198925172337536,3139847906307949696,6322070093095493504,198027271140075136,5115463180914712448,2269520028411874816,3345752830365960320,150197587618319744,3899393459350372224,135885416558354048,1917682526636770688,1366925946711444480,4031634570385585152,326760119744747392,356764413385350144,3385237181976223104,928827570144344448,720454586079843840,219651916081208320,2622525894434166272,3250328209054347264,351045720262686080,877028546568262784,3357701803041885696,4595155617018571008,1350982413929937920,1396617472242087168,1941126622803033984,1851787179879007232,964064748856974464,3383405537340380416,3421775057173721600,418582156851693824,819071050989217792,1785074513721959552,1950040638449191424,117990177621007744,1533184169394818304,962092607249662592,1401005829306968064,47917816253918720,47729215646206080,3219132482897057152,3339921875389105152,1290392657450571008,1475079309195354880,2101992694430576256,5134635708766250752,226855435229242496,1308058064097405696,1428030622526979968,1439069444391326208,1022456139210632064,819441178386727680,1022456104850892928,1362592672604119168,3378334482336389760,1229977414080680192,522863309964987520,4347870370990204928,1306277920412876800,386655019234959872,2118424350249708800,426641955043723520,4282578724832056576,6562924609150908416,3800590554204451712,5138510181584617856,385334230892516480,4293318823182081408,1428427236986209024,3903318372263850368,2306965202564744064,3478160727866058368,762920503987026816,1363409369224902016,151866165232956544,122043664675692800,347471207961250048,1362884318063104640,168774798644094592,119736889281099136,758200712885953280,898506166187633280,1013652173512807040,778671836983753088,219426653636581248,929741264307571968,159559619890954752,170712584810347904,1534831272173203072,39527339939738112,6244712475056967936,1310513342280948480,1905055700744817024,393155984814848128,886057182003477760,2616132101175106816,163152549013270400,3795993633527490560,328643239565641856,4602078902438063488,2119839387352940288,1992715605301433856,834162608290205312,2855743172658367360,920904008319029760,1363678268537372544,5951824121022278144,1149897160435827200,4242728884389090944,6002807341299977216,1412432297740307456,4780294722094459904,3418324583527645440,4213581106021661184,4017860992519744384,1495487688115551744,1710948192852697600,43574131143039104,112157612034669440,5664814198431308288,4518262684390915200,6418732764501078784,3652796572020424448,3187115498866675456,6446274293824799488,2640434056928150400,5975663354131618304,1810616448010879488,4330690742322011520,3796072592206250624,786834302080370304,6663600360560306560,4472832130942575872,4810594479418041856,6794047652729201024,4764027962957023104,3988689609004982912,4572835535272627712,654687847820642560,6553614253923452800,3209938366665770752,3409711211681795584,762815470562110464,6603693881832177792,4075141768785646848,1554433777791815808,2627117287488522240,2603090003484152064,4393265392168829056,5413438219396893568,4946938113149426944,3737308025029348608,1214160733157163008,2400808142038361088,3231945508509506176,6371169987426204928,1051547052218220160,530158019855216896,5169649072437050496,3828238392559860992,4031586157514097024,4010201828880793984,2683023811628007296,4536614495522394112,2830099469122381056,2940856402123426176,3738099879558957952)
    ' for job 'ffe783a4-3242-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

In [47]:
from astroquery.gaia import Gaia

tables = Gaia.load_tables(only_names=True)
table_names = [t.get_qualified_name() for t in tables]

print("num tables:", len(table_names))
print([x for x in table_names if "astrophysical" in x.lower()][:20])
print([x for x in table_names if "gaiadr3" in x.lower()][:50])

INFO: Retrieving tables... [astroquery.utils.tap.core]
500 Error 500:
esavo.tap.TAPException: java.sql.SQLException: esavo.tap.db.DBException: Can not execute the following SQL:
SELECT argument_name, description, arg_type, default_value, max_value, min_value, arraysize  FROM tap_schema.functions_arguments where all_functions_id=809 ORDER BY arg_order ASC
Because: ERROR: failed to acquire resources on one or more segments
  Detail: could not connect to server: Cannot assign requested address
	Is the server running on host "10.0.3.174" and accepting
	TCP/IP connections on port 55000?
 (seg0 10.0.3.174:55000)

HTTPError: Error 500:
esavo.tap.TAPException: java.sql.SQLException: esavo.tap.db.DBException: Can not execute the following SQL:
SELECT argument_name, description, arg_type, default_value, max_value, min_value, arraysize  FROM tap_schema.functions_arguments where all_functions_id=809 ORDER BY arg_order ASC
Because: ERROR: failed to acquire resources on one or more segments
  Detail: could not connect to server: Cannot assign requested address
	Is the server running on host "10.0.3.174" and accepting
	TCP/IP connections on port 55000?
 (seg0 10.0.3.174:55000)

In [49]:
try:
    test_query = """
    SELECT TOP 5 *
    FROM gaiadr3.astrophysical_parameters
    """
    job = Gaia.launch_job(test_query)
    res = job.get_results()
    print(res.colnames)
    print(res[:2])
except Exception as e:
    print(type(e).__name__)
    print(e)

['solution_id', 'source_id', 'classprob_dsc_combmod_quasar', 'classprob_dsc_combmod_galaxy', 'classprob_dsc_combmod_star', 'classprob_dsc_combmod_whitedwarf', 'classprob_dsc_combmod_binarystar', 'classprob_dsc_specmod_quasar', 'classprob_dsc_specmod_galaxy', 'classprob_dsc_specmod_star', 'classprob_dsc_specmod_whitedwarf', 'classprob_dsc_specmod_binarystar', 'classprob_dsc_allosmod_quasar', 'classprob_dsc_allosmod_galaxy', 'classprob_dsc_allosmod_star', 'teff_gspphot', 'teff_gspphot_lower', 'teff_gspphot_upper', 'logg_gspphot', 'logg_gspphot_lower', 'logg_gspphot_upper', 'mh_gspphot', 'mh_gspphot_lower', 'mh_gspphot_upper', 'distance_gspphot', 'distance_gspphot_lower', 'distance_gspphot_upper', 'azero_gspphot', 'azero_gspphot_lower', 'azero_gspphot_upper', 'ag_gspphot', 'ag_gspphot_lower', 'ag_gspphot_upper', 'abp_gspphot', 'abp_gspphot_lower', 'abp_gspphot_upper', 'arp_gspphot', 'arp_gspphot_lower', 'arp_gspphot_upper', 'ebpminrp_gspphot', 'ebpminrp_gspphot_lower', 'ebpminrp_gspphot_upper', 'mg_gspphot', 'mg_gspphot_lower', 'mg_gspphot_upper', 'radius_gspphot', 'radius_gspphot_lower', 'radius_gspphot_upper', 'logposterior_gspphot', 'mcmcaccept_gspphot', 'libname_gspphot', 'teff_gspspec', 'teff_gspspec_lower', 'teff_gspspec_upper', 'logg_gspspec', 'logg_gspspec_lower', 'logg_gspspec_upper', 'mh_gspspec', 'mh_gspspec_lower', 'mh_gspspec_upper', 'alphafe_gspspec', 'alphafe_gspspec_lower', 'alphafe_gspspec_upper', 'fem_gspspec', 'fem_gspspec_lower', 'fem_gspspec_upper', 'fem_gspspec_nlines', 'fem_gspspec_linescatter', 'sife_gspspec', 'sife_gspspec_lower', 'sife_gspspec_upper', 'sife_gspspec_nlines', 'sife_gspspec_linescatter', 'cafe_gspspec', 'cafe_gspspec_lower', 'cafe_gspspec_upper', 'cafe_gspspec_nlines', 'cafe_gspspec_linescatter', 'tife_gspspec', 'tife_gspspec_lower', 'tife_gspspec_upper', 'tife_gspspec_nlines', 'tife_gspspec_linescatter', 'mgfe_gspspec', 'mgfe_gspspec_lower', 'mgfe_gspspec_upper', 'mgfe_gspspec_nlines', 'mgfe_gspspec_linescatter', 'ndfe_gspspec', 'ndfe_gspspec_lower', 'ndfe_gspspec_upper', 'ndfe_gspspec_nlines', 'ndfe_gspspec_linescatter', 'feiim_gspspec', 'feiim_gspspec_lower', 'feiim_gspspec_upper', 'feiim_gspspec_nlines', 'feiim_gspspec_linescatter', 'sfe_gspspec', 'sfe_gspspec_lower', 'sfe_gspspec_upper', 'sfe_gspspec_nlines', 'sfe_gspspec_linescatter', 'zrfe_gspspec', 'zrfe_gspspec_lower', 'zrfe_gspspec_upper', 'zrfe_gspspec_nlines', 'zrfe_gspspec_linescatter', 'nfe_gspspec', 'nfe_gspspec_lower', 'nfe_gspspec_upper', 'nfe_gspspec_nlines', 'nfe_gspspec_linescatter', 'crfe_gspspec', 'crfe_gspspec_lower', 'crfe_gspspec_upper', 'crfe_gspspec_nlines', 'crfe_gspspec_linescatter', 'cefe_gspspec', 'cefe_gspspec_lower', 'cefe_gspspec_upper', 'cefe_gspspec_nlines', 'cefe_gspspec_linescatter', 'nife_gspspec', 'nife_gspspec_lower', 'nife_gspspec_upper', 'nife_gspspec_nlines', 'nife_gspspec_linescatter', 'cn0ew_gspspec', 'cn0ew_gspspec_uncertainty', 'cn0_gspspec_centralline', 'cn0_gspspec_width', 'dib_gspspec_lambda', 'dib_gspspec_lambda_uncertainty', 'dibew_gspspec', 'dibew_gspspec_uncertainty', 'dibewnoise_gspspec_uncertainty', 'dibp0_gspspec', 'dibp2_gspspec', 'dibp2_gspspec_uncertainty', 'dibqf_gspspec', 'flags_gspspec', 'logchisq_gspspec', 'ew_espels_halpha', 'ew_espels_halpha_uncertainty', 'ew_espels_halpha_flag', 'ew_espels_halpha_model', 'classlabel_espels', 'classlabel_espels_flag', 'classprob_espels_wcstar', 'classprob_espels_wnstar', 'classprob_espels_bestar', 'classprob_espels_ttauristar', 'classprob_espels_herbigstar', 'classprob_espels_dmestar', 'classprob_espels_pne', 'azero_esphs', 'azero_esphs_uncertainty', 'ag_esphs', 'ag_esphs_uncertainty', 'ebpminrp_esphs', 'ebpminrp_esphs_uncertainty', 'teff_esphs', 'teff_esphs_uncertainty', 'logg_esphs', 'logg_esphs_uncertainty', 'vsini_esphs', 'vsini_esphs_uncertainty', 'flags_esphs', 'spectraltype_esphs', 'activityindex_espcs', 'activityindex_espcs_uncertainty', 'activityindex_espcs_input', 'teff_espucd', 'teff_espucd_uncertainty', 'flags_espucd', 'radius_flame', 'radius_flame_lower', 'radius_flame_upper', 'lum_flame', 'lum_flame_lower', 'lum_flame_upper', 'mass_flame', 'mass_flame_lower', 'mass_flame_upper', 'age_flame', 'age_flame_lower', 'age_flame_upper', 'flags_flame', 'evolstage_flame', 'gravredshift_flame', 'gravredshift_flame_lower', 'gravredshift_flame_upper', 'bc_flame', 'mh_msc', 'mh_msc_upper', 'mh_msc_lower', 'azero_msc', 'azero_msc_upper', 'azero_msc_lower', 'distance_msc', 'distance_msc_upper', 'distance_msc_lower', 'teff_msc1', 'teff_msc1_upper', 'teff_msc1_lower', 'teff_msc2', 'teff_msc2_upper', 'teff_msc2_lower', 'logg_msc1', 'logg_msc1_upper', 'logg_msc1_lower', 'logg_msc2', 'logg_msc2_upper', 'logg_msc2_lower', 'ag_msc', 'ag_msc_upper', 'ag_msc_lower', 'logposterior_msc', 'mcmcaccept_msc', 'mcmcdrift_msc', 'flags_msc', 'neuron_oa_id', 'neuron_oa_dist', 'neuron_oa_dist_percentile_rank', 'flags_oa']
    solution_id       source_id   ... neuron_oa_dist_percentile_rank flags_oa
                                  ...
------------------- ------------- ... ------------------------------ --------
1636148068921376768 1340029955712 ...                             --
1636148068921376768 5050881701504 ...                             --

WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm. [astropy.units.format.base]

In [51]:
from astroquery.gaia import Gaia
import pandas as pd

def query_gaia_by_source_ids(source_ids):
    ids_str = ",".join(source_ids)

    query = f"""
    SELECT
        source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id IN ({ids_str})
    """
    job = Gaia.launch_job(query)
    return job.get_results().to_pandas()

In [52]:
def query_astrophysical_by_source_ids(source_ids):
    ids_str = ",".join(source_ids)

    query = f"""
    SELECT
        source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id IN ({ids_str})
    """
    job = Gaia.launch_job(query)
    return job.get_results().to_pandas()

In [55]:
from astroquery.gaia import Gaia

q1 = """
SELECT TOP 5
    source_id,
    phot_g_mean_mag,
    phot_bp_mean_mag,
    phot_rp_mean_mag,
    bp_rp,
    ruwe
FROM gaiadr3.gaia_source
"""
job1 = Gaia.launch_job(q1)
res1 = job1.get_results()
print(res1.colnames)
print(res1[:2])

['source_id', 'phot_g_mean_mag', 'phot_bp_mean_mag', 'phot_rp_mean_mag', 'bp_rp', 'ruwe']
  source_id   phot_g_mean_mag phot_bp_mean_mag ...   bp_rp      ruwe
                    mag             mag        ...    mag
------------- --------------- ---------------- ... --------- ---------
1752346816896       19.060192        20.177439 ... 2.0861473 0.9940326
2753074326400       19.975853         21.10666 ... 2.2815895 1.0328494

In [56]:
q2 = """
SELECT TOP 5
    source_id,
    ebpminrp_gspphot
FROM gaiadr3.astrophysical_parameters
"""
job2 = Gaia.launch_job(q2)
res2 = job2.get_results()
print(res2.colnames)
print(res2[:2])

['source_id', 'ebpminrp_gspphot']
  source_id   ebpminrp_gspphot
                    mag
------------- ----------------
1374389600384           0.1986
3607772690688           0.0153

In [ ]:
from astroquery.gaia import Gaia

def query_gaia_by_source_ids(source_ids):
    ids_str = ",".join(str(x) for x in source_ids)

    query = (
        "SELECT "
        "source_id, ra, dec, parallax, parallax_error, pmra, pmdec, "
        "phot_g_mean_mag, phot_bp_mean_mag, phot_rp_mean_mag, bp_rp, ruwe "
        "FROM gaiadr3.gaia_source "
        f"WHERE source_id IN ({ids_str})"
    )

    job = Gaia.launch_job(query)
    return job.get_results().to_pandas()


def query_astrophysical_by_source_ids(source_ids):
    ids_str = ",".join(str(x) for x in source_ids)

    query = (
        "SELECT "
        "source_id, ebpminrp_gspphot "
        "FROM gaiadr3.astrophysical_parameters "
        f"WHERE source_id IN ({ids_str})"
    )

    job = Gaia.launch_job(query)
    return job.get_results().to_pandas()

In [ ]:
def query_gaia_one_source_id(source_id):
    query = f"""
    SELECT
        source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = {int(source_id)}
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    return r.to_pandas()
def query_ap_one_source_id(source_id):
    query = f"""
    SELECT
        source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = {int(source_id)}
    """
    job = Gaia.launch_job(query)
    r = job.get_results()
    return r.to_pandas()

In [66]:
sid = direct_ids[0]

core_one = query_gaia_one_source_id(sid)
ap_one = query_ap_one_source_id(sid)

print(core_one)
print(ap_one)

             source_id          ra        dec   parallax  parallax_error  \
0  5932005595773303040  246.759296 -54.197154  21.820558        0.014829

        pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
0  19.540099  65.965484        10.955764         11.769478         10.074646

      bp_rp      ruwe
0  1.694832  0.796916
             source_id  ebpminrp_gspphot
0  5932005595773303040               NaN

In [67]:
import pandas as pd

core_rows = []
ap_rows = []

for i, sid in enumerate(direct_ids, start=1):
    if i % 25 == 0:
        print(f"{i}/{len(direct_ids)}")

    try:
        c = query_gaia_one_source_id(sid)
        if len(c) > 0:
            core_rows.append(c)

        a = query_ap_one_source_id(sid)
        if len(a) > 0:
            ap_rows.append(a)

    except Exception as e:
        print(f"failed for {sid}: {e}")

failed for 6177238671977087360: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 6177238671977087360
    ' for job 'aaf3c678-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 4149820284980989184: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 4149820284980989184
    ' for job 'b004c5c6-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 661794060190112000: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 661794060190112000
    ' for job 'b2d3280d-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 2485305370114328576: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 2485305370114328576
    ' for job 'b4994214-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 1130450270073924608: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1130450270073924608
    ' for job 'b6fa157e-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 6885776098199761024: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 6885776098199761024
    ' for job 'b9f77707-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 3817534337625985280: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3817534337625985280
    ' for job 'bbbccdbb-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 222749343414443648: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 222749343414443648
    ' for job 'bed9c537-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 220989197096055040: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 220989197096055040
    ' for job 'c094e2bb-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 4201781696994082944: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 4201781696994082944
    ' for job 'c37d35a8-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 5717278911884264576: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 5717278911884264576
    ' for job 'c67a9734-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 2871730758921709952: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 2871730758921709952
    ' for job 'c82fe857-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 3738752852026813184: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3738752852026813184
    ' for job 'cab114ff-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 3195919254111314816: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3195919254111314816
    ' for job 'cf34ef7b-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 1600882199829338368: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1600882199829338368
    ' for job 'd263e851-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

25/261
failed for 5853498713190525696: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 5853498713190525696
    ' for job 'd44615d4-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 1996725077535282944: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1996725077535282944
    ' for job 'd724569f-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 975968718869126144: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 975968718869126144
    ' for job 'd996dd47-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 3340477717172813568: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3340477717172813568
    ' for job 'dbe75d00-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 67198925172337536: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 67198925172337536
    ' for job 'ddbbf5f5-3245-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 6322070093095493504: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 6322070093095493504
    ' for job 'e0d8c664-3245-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !

[             source_id          ra        dec   parallax  parallax_error  \
 0  5932005595773303040  246.759296 -54.197154  21.820558        0.014829

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  19.540099  65.965484        10.955764         11.769478         10.074646

       bp_rp      ruwe
 0  1.694832  0.796916  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  3930922058356114432  191.80433  14.704564  16.498496        0.021312

         pmra   pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -354.72243  149.31         12.77739         13.775156         11.784307

       bp_rp     ruwe
 0  1.990849  1.22336  ,
              source_id         ra       dec   parallax  parallax_error  \
 0  3175193288128400768  65.432288 -16.00092  21.355441        0.029057

         pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  267.44587 -171.730706        11.713509         12.747372         10.687969

       bp_rp     ruwe
 0  2.059402  2.01766  ,
             source_id          ra        dec   parallax  parallax_error  \
 0  908364387441657472  125.016591  38.576947  22.524347        0.018565

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0 -181.910451 -256.608143        12.280472         13.390044

    phot_rp_mean_mag     bp_rp      ruwe
 0         11.235033  2.155011  1.305746  ,
              source_id        ra       dec  parallax  parallax_error  \
 0  2485305370114328576  20.81637 -2.145728  23.15137        0.031866

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  233.95583  37.652015         11.71621         12.845122         10.654177

       bp_rp      ruwe
 0  2.190946  1.559819  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  1130450270073924608  146.703635  76.03947  63.325063         0.01529

         pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  87.366751 -1000.440302         9.792734         10.867223

    phot_rp_mean_mag     bp_rp      ruwe
 0          8.757159  2.110064  1.044251  ,
             source_id          ra       dec   parallax  parallax_error  \
 0  577602496345490176  133.781957  1.541856  48.740434        0.018375

         pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  44.943995 -1045.875843         9.289488         10.186295

    phot_rp_mean_mag     bp_rp      ruwe
 0          8.353907  1.832388  1.062343  ,
              source_id          ra       dec  parallax  parallax_error  \
 0  3817534337625985280  170.875095  7.024697  27.02506        0.469243

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  172.105635 -49.879621         9.833677         10.587264          8.950231

       bp_rp       ruwe
 0  1.637033  27.549984  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  3931313793733241088  194.096708  15.689892  17.387858        0.015067

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -478.457793 -1311.2805        13.252852         14.039905         12.386014

       bp_rp      ruwe
 0  1.653891  1.121143  ,
             source_id         ra        dec   parallax  parallax_error  \
 0  220989197096055040  52.689416  34.012001  36.654431         0.03387

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  497.882318 -1499.31128        12.035498         12.980215

    phot_rp_mean_mag     bp_rp      ruwe
 0         11.070039  1.910176  1.266651  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  4201781696994082944  290.139095 -7.662944  95.178395        0.031006

         pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -70.590994 -177.974037        10.972157         12.369064          9.807171

       bp_rp      ruwe
 0  2.561893  1.169582  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  4021566209266336640  176.482353  31.824102  31.638878        0.364214

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0 -165.447822 -260.013525        12.808223         14.304039

    phot_rp_mean_mag     bp_rp       ruwe
 0         11.611558  2.692481  18.951975  ,
              source_id          ra        dec    parallax  parallax_error  \
 0  5717278911884264576  115.086083 -17.415138  109.254482        0.039175

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  1152.24304 -536.411721         13.95689         16.885386

    phot_rp_mean_mag     bp_rp      ruwe
 0         12.506049  4.379336  1.086701  ,
              source_id          ra        dec  parallax  parallax_error  pmra  \
 0  2871730758921709952  355.970173  32.593828       NaN             NaN   NaN

    pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag     bp_rp  ruwe
 0    NaN        10.610644         11.941395          9.431913  2.509481   NaN  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  3738752852026813184  204.787747  12.156739  19.279788        0.023064

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  122.242085 -133.244941        13.015613         14.282706

    phot_rp_mean_mag     bp_rp      ruwe
 0         11.902324  2.380383  1.222516  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  3630015546177181952  202.506642 -8.709179  62.280692        0.041981

           pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0 -1114.015319 -473.858639         12.70625         14.502465

    phot_rp_mean_mag     bp_rp      ruwe
 0         11.427612  3.074853  1.570442  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  5402903764121955840  170.839979 -32.383247  10.847826        0.038403

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -228.308296  40.810834        15.117716         16.706141         13.900269

       bp_rp      ruwe
 0  2.805872  1.179064  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  1600882199829338368  227.97151  56.413146  17.417677        0.018178

         pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -222.71038 -294.739825        14.626679         16.048891         13.456678

       bp_rp      ruwe
 0  2.592213  1.219304  ,
              source_id          ra        dec    parallax  parallax_error  \
 0  5853498713190525696  217.392321 -62.676075  768.066539        0.049873

           pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0 -3781.741008  769.465015         8.984749         11.373116

    phot_rp_mean_mag    bp_rp      ruwe
 0          7.568535  3.80458  0.971453  ,
             source_id          ra        dec   parallax  parallax_error  \
 0  946030529073022080  107.555496  37.668316  44.600835        0.436864

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0 -209.281534 -280.808809        13.232475         14.892705

    phot_rp_mean_mag     bp_rp       ruwe
 0         11.992752  2.899953  33.123741  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  1379500928055726848  241.208684  39.160165  69.637451        0.019234

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -562.853602  42.231001        12.854803          14.52069         11.612505

       bp_rp      ruwe
 0  2.908185  1.145357  ,
              source_id          ra       dec    parallax  parallax_error  \
 0  3098328182579892096  122.994683  8.750402  147.721849        0.094957

           pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  1069.811738 -5094.220103        11.397289         13.130089

    phot_rp_mean_mag     bp_rp      ruwe
 0         10.137975  2.992114  2.096868  ,
            source_id         ra        dec   parallax  parallax_error  \
 0  67198925172337536  59.977224  26.088755  43.647234        0.352649

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  730.915702 -255.852034        11.467834         12.857243

    phot_rp_mean_mag     bp_rp       ruwe
 0          10.29845  2.558793  12.874119  ,
              source_id          ra       dec    parallax  parallax_error  \
 0  3139847906307949696  111.854628  5.209383  264.126898         0.04128

          pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  571.232347 -3691.486565         8.576388         10.111705

    phot_rp_mean_mag     bp_rp     ruwe
 0          7.353947  2.757758  1.23877  ,
             source_id         ra       dec   parallax  parallax_error  \
 0  198027271140075136  88.932447  46.84708  33.562484         0.01885

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  12.720574 -529.43704        14.059253         15.755185         12.813098

       bp_rp      ruwe
 0  2.942087  1.170622  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  5115463180914712448  54.572022 -11.499069  61.886051        0.021999

           pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  1458.200738 -2696.545125        12.066338         13.255437

    phot_rp_mean_mag     bp_rp      ruwe
 0         10.986762  2.268675  1.449551  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  3345752830365960320  93.510058  15.159632  23.745342        0.019456

          pmra        pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  750.011876 -1226.426005        13.765578         14.881888

    phot_rp_mean_mag     bp_rp      ruwe
 0         12.716496  2.165393  1.129493  ,
             source_id         ra        dec   parallax  parallax_error  \
 0  150197587618319744  63.380393  25.177115  11.691108        0.018288

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -17.985222  13.744543        13.826035         15.051762         12.728703

       bp_rp      ruwe
 0  2.323059  1.108692  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  3899393459350372224  177.986195  7.523672  19.705246        0.028009

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -126.451092 -81.683746        11.408315          12.59398         10.320908

       bp_rp      ruwe
 0  2.273072  1.182947  ,
              source_id          ra        dec  parallax  parallax_error  \
 0  1917682526636770688  348.135053  39.192466  13.15236        0.014185

        pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  50.50087 -9.741176        13.542837         14.879381         12.400732

       bp_rp      ruwe
 0  2.478649  1.098103  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  1366925946711444480  264.24701  48.996744  18.332592        0.179272

        pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -2.181373  145.38783        12.164504         13.448789          11.03691

       bp_rp      ruwe
 0  2.411879  15.11123  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  4031634570385585152  178.237571  35.91288  25.142112        0.026488

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -99.860989  23.798305        12.636212           13.9568         11.497874

       bp_rp      ruwe
 0  2.458925  1.666515  ,
             source_id         ra        dec   parallax  parallax_error  \
 0  326760119744747392  37.401319  34.394804  26.028142        0.097922

         pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -47.663864 -111.360359        11.586893         12.717959         10.524907

       bp_rp      ruwe
 0  2.193052  5.255462  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  3385237181976223104  102.951301  27.201294  21.846772        0.018615

        pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -6.082921 -115.617519        11.296736         12.187493         10.364001

       bp_rp      ruwe
 0  1.823492  1.011742  ,
             source_id          ra       dec   parallax  parallax_error  \
 0  928827570144344448  123.953398  46.02177  23.113187        0.019871

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -118.913889 -75.391374        12.266249         13.431188         11.194427

       bp_rp      ruwe
 0  2.236761  1.429419  ,
             source_id         ra        dec  parallax  parallax_error  \
 0  219651916081208320  57.198964  35.082634  9.356378        0.015938

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  33.405934 -42.294807        13.300276         14.345949         12.279472

       bp_rp      ruwe
 0  2.066477  1.081802  ,
              source_id         ra       dec   parallax  parallax_error  \
 0  3250328209054347264  56.848058 -1.973426  59.431994        0.028812

          pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  \
 0  180.640204 -274.016231        10.505774         11.839527

    phot_rp_mean_mag     bp_rp      ruwe
 0          9.359375  2.480152  1.519676  ,
             source_id         ra        dec  parallax  parallax_error  \
 0  877028546568262784  121.73904  30.698481  4.676318        0.124812

        pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  2.543979 -77.561826        14.442828         15.432125         13.438025

     bp_rp      ruwe
 0  1.9941  5.436591  ,
              source_id          ra      dec   parallax  parallax_error  \
 0  3357701803041885696  101.690104  15.9616  44.688318        0.019713

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -99.319104 -25.349881        10.243071         11.285658           9.23299

       bp_rp     ruwe
 0  2.052668  1.08669  ,
              source_id          ra        dec  parallax  parallax_error  pmra  \
 0  4595155617018571008  261.831565  27.150208       NaN             NaN   NaN

    pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag     bp_rp  ruwe
 0    NaN          12.7884         13.751482          11.29042  2.461062   NaN  ,
              source_id          ra        dec  parallax  parallax_error  \
 0  1350982413929937920  269.455514  47.274254   7.03025        0.012047

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -13.691395 -65.953011        14.034032         15.107383         12.999323

      bp_rp      ruwe
 0  2.10806  1.042919  ,
              source_id          ra       dec  parallax  parallax_error  \
 0  1396617472242087168  236.595972  44.05418  21.49916        0.013169

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -86.917406  17.573769        11.226166         12.083434          10.31621

       bp_rp      ruwe
 0  1.767224  1.140244  ,
              source_id          ra       dec  parallax  parallax_error  \
 0  1851787179879007232  319.640961  30.24285  26.75901        0.017548

         pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  59.352929 -22.44423        10.937753         11.932399          9.945482

       bp_rp     ruwe
 0  1.986917  1.17442  ,
             source_id         ra        dec   parallax  parallax_error  \
 0  964064748856974464  99.943956  43.051082  16.224594         0.06567

        pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -6.195175 -115.244274        12.624192         13.942026         11.480688

       bp_rp      ruwe
 0  2.461338  5.459238  ,
              source_id        ra        dec  parallax  parallax_error  \
 0  3383405537340380416  96.56052  23.826773   36.3393        0.023231

         pmra       pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -10.788024 -136.233845        10.995646          12.08765          9.955789

       bp_rp     ruwe
 0  2.131862  1.07082  ,
             source_id       ra        dec   parallax  parallax_error  \
 0  418582156851693824  9.14362  55.626684  22.928541         0.01905

         pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  55.091858 -9.893502        11.322371         12.254256         10.366407

       bp_rp      ruwe
 0  1.887849  1.109268  ,
             source_id          ra        dec   parallax  parallax_error  \
 0  819071050989217792  139.752728  46.181998  33.391463        0.025435

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -151.05512 -21.336045        11.151594         12.253352         10.105474

       bp_rp      ruwe
 0  2.147878  1.276181  ,
              source_id          ra       dec   parallax  parallax_error  \
 0  1785074513721959552  318.924975  17.77343  13.946858        0.400157

         pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  58.845546 -0.199788        12.249537         13.298705         11.206197

       bp_rp       ruwe
 0  2.092508  28.173262  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  1950040638449191424  329.259918  38.442292  13.352888         0.01295

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  203.008294  46.623071        11.979858          12.80361         11.081624

       bp_rp      ruwe
 0  1.721986  1.250741  ,
              source_id          ra        dec   parallax  parallax_error  \
 0  1533184169394818304  186.200212  40.726978  21.597979        0.032043

          pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -163.799597 -10.126605        11.271945         12.183311          10.32058

       bp_rp      ruwe
 0  1.862731  1.459928  ,
             source_id         ra       dec   parallax  parallax_error  \
 0  962092607249662592  95.842849  43.74141  17.878284        0.109836

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  19.512978 -83.651286        12.528999         13.724881         11.441647

       bp_rp     ruwe
 0  2.283235  7.29041  ,
            source_id         ra        dec   parallax  parallax_error  \
 0  47917816253918720  66.311137  18.973456  18.569708        0.032179

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0  97.281081 -28.887608        11.957183         12.925601         10.876818

       bp_rp      ruwe
 0  2.048783  2.037797  ,
              source_id         ra       dec   parallax  parallax_error  \
 0  3219132482897057152  86.824532 -0.013866  38.556498         0.01737

         pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -74.880783 -70.65399        10.206772         11.155877          9.242287

      bp_rp      ruwe
 0  1.91359  1.052855  ,
              source_id         ra        dec   parallax  parallax_error  \
 0  1290392657450571008  227.66227  33.689144  30.713532        0.012747

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -115.71038 -45.817593        10.411062         11.292404          9.487696

       bp_rp      ruwe
 0  1.804708  1.161826  ,
              source_id          ra        dec  parallax  parallax_error  \
 0  1475079309195354880  203.386791  36.695764  8.600569        0.127167

         pmra     pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \
 0 -54.122797 -9.991544        13.161207          14.15399         12.150093

       bp_rp       ruwe
 0  2.003897  11.507676  ,
              source_id          ra       dec  parallax  parallax_error  \
 0  2101992694430576256  290.384072  42.51521  31.47194        0.202425

         pmra      pmdec  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag  \

In [69]:
gaia_core = pd.concat(core_rows, ignore_index=True)
gaia_ap = pd.concat(ap_rows, ignore_index=True)

gaia_direct = gaia_core.merge(gaia_ap, how="left", on="source_id")
gaia_direct["g_rp"] = gaia_direct["phot_g_mean_mag"] - gaia_direct["phot_rp_mean_mag"]
gaia_direct["bp_rp_0"] = gaia_direct["bp_rp"] - gaia_direct["ebpminrp_gspphot"]

In [70]:
gaia_direct

,source_id,ra,dec,parallax,parallax_error,pmra,pmdec,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,bp_rp,ruwe,ebpminrp_gspphot,g_rp,bp_rp_0
0,5932005595773303040,246.759296,-54.197154,21.820558,0.014829,19.540099,65.965484,10.955764,11.769478,10.074646,1.694832,0.796916,NaN,0.881118,NaN
1,3930922058356114432,191.804330,14.704564,16.498496,0.021312,-354.722430,149.310000,12.777390,13.775156,11.784307,1.990849,1.223360,NaN,0.993083,NaN
2,3175193288128400768,65.432288,-16.000920,21.355441,0.029057,267.445870,-171.730706,11.713509,12.747372,10.687969,2.059402,2.017660,NaN,1.025539,NaN
3,908364387441657472,125.016591,38.576947,22.524347,0.018565,-181.910451,-256.608143,12.280472,13.390044,11.235033,2.155011,1.305746,0.0002,1.045439,2.154811
4,2485305370114328576,20.816370,-2.145728,23.151370,0.031866,233.955830,37.652015,11.716210,12.845122,10.654177,2.190946,1.559819,NaN,1.062034,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,6814962601568904576,324.758758,-24.161181,51.399140,0.070609,1003.987424,-710.657765,12.077593,13.643229,10.848627,2.794601,1.540514,NaN,1.228966,NaN
184,5686163724944033792,148.173530,-15.604420,56.820684,0.021463,-118.933799,-134.089874,12.172839,13.689925,10.970720,2.719205,1.240200,NaN,1.202119,NaN
185,6044721476534419584,248.852636,-27.319139,50.826196,0.030425,-5.798222,-894.853226,12.750803,14.414499,11.505672,2.908827,1.249603,0.0001,1.245131,2.908727
186,5329084752471816192,131.159854,-48.085631,68.700905,0.017307,-321.970547,794.451801,12.434480,14.191856,11.165983,3.025873,1.062990,0.0000,1.268497,3.025873
187,6469383588698276480,306.903634,-54.882223,57.820214,0.026248,-258.052799,200.546742,11.546468,12.989694,10.370600,2.619094,1.164507,NaN,1.175868,NaN

In [71]:
df["gaia_dr3_source_id_from_simbad"] = df["gaia_dr3_source_id_from_simbad"].astype("string")
gaia_direct["source_id"] = gaia_direct["source_id"].astype("string")

df = df.merge(
    gaia_direct,
    how="left",
    left_on="gaia_dr3_source_id_from_simbad",
    right_on="source_id"
)

In [72]:
df[[
    "star_name",
    "gaia_dr3_source_id_from_simbad",
    "bp_rp",
    "g_rp",
    "ruwe",
    "ebpminrp_gspphot",
    "bp_rp_0"
]].head(20)

,star_name,gaia_dr3_source_id_from_simbad,bp_rp,g_rp,ruwe,ebpminrp_gspphot,bp_rp_0
0,L266-195,5932005595773303040,1.694832,0.881118,0.796916,NaN,NaN
1,LP 856-54,6177238671977087360,NaN,NaN,NaN,NaN,NaN
2,G59-39,3930922058356114432,1.990849,0.993083,1.223360,NaN,NaN
3,LP 775-52,3175193288128400768,2.059402,1.025539,2.017660,NaN,NaN
4,GJ 2131 A,4149820284980989184,NaN,NaN,NaN,NaN,NaN
5,G111-72,908364387441657472,2.155011,1.045439,1.305746,0.0002,2.154811
6,HIP 43232 B,661794060190112000,NaN,NaN,NaN,NaN,NaN
7,LP 587-54,2485305370114328576,2.190946,1.062034,1.559819,NaN,NaN
8,GJ 366,1130450270073924608,2.110064,1.035575,1.044251,NaN,NaN
9,GJ 328,577602496345490176,1.832388,0.935581,1.062343,0.0005,1.831888
10,GJ 821,6885776098199761024,NaN,NaN,NaN,NaN,NaN
11,LP 552-48,3817534337625985280,1.637033,0.883447,27.549984,NaN,NaN
12,LHS 343,3931313793733241088,1.653891,0.866838,1.121143,0.0004,1.653491
13,LHS 173,222749343414443648,NaN,NaN,NaN,NaN,NaN
14,LHS 174,220989197096055040,1.910176,0.965459,1.266651,NaN,NaN
15,NSV 11919,4201781696994082944,2.561893,1.164986,1.169582,NaN,NaN
16,Gaia DR3 75525a,<NA>,NaN,NaN,NaN,NaN,NaN
17,G148-6,4021566209266336640,2.692481,1.196665,18.951975,NaN,NaN
18,LP 783-2,5717278911884264576,4.379336,1.450841,1.086701,NaN,NaN
19,G130-6,2871730758921709952,2.509481,1.178731,NaN,NaN,NaN

In [73]:
df["bp_rp"].notna().sum(), len(df)

(np.int64(237), 380)

In [74]:
gaia_direct[["bp_rp", "g_rp", "ruwe", "ebpminrp_gspphot", "bp_rp_0"]].describe()

            bp_rp        g_rp        ruwe  ebpminrp_gspphot    bp_rp_0
count  188.000000  188.000000  185.000000         51.000000  51.000000
mean     2.460768    1.130528    2.547583          0.015529   2.338650
std      0.464516    0.126019    4.562168          0.055836   0.381499
min      1.637033    0.866838    0.796916          0.000000   1.653491
25%      2.091349    1.034778    1.084851          0.000000   2.047809
50%      2.439629    1.138288    1.186639          0.000100   2.293731
75%      2.794490    1.227675    1.449551          0.000250   2.621484
max      4.379336    1.497980   33.123741          0.240500   3.139298

In [75]:
failed_ids = []

core_rows = []
ap_rows = []

for i, sid in enumerate(direct_ids, start=1):
    if i % 25 == 0:
        print(f"{i}/{len(direct_ids)}")

    try:
        c = query_gaia_one_source_id(sid)
        if len(c) > 0:
            core_rows.append(c)

        a = query_ap_one_source_id(sid)
        if len(a) > 0:
            ap_rows.append(a)

    except Exception as e:
        failed_ids.append((sid, str(e)))
        print(f"failed for {sid}: {e}")

failed for 6177238671977087360: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 6177238671977087360
    ' for job '91449ff9-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 3930922058356114432: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3930922058356114432
    ' for job '938679b0-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 4149820284980989184: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 4149820284980989184
    ' for job '967498ff-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 661794060190112000: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 661794060190112000
    ' for job '98e59910-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 2485305370114328576: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 2485305370114328576
    ' for job '9abcca15-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 1130450270073924608: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1130450270073924608
    ' for job '9d0c1150-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 577602496345490176: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 577602496345490176
    ' for job '9f9cce58-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 6885776098199761024: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 6885776098199761024
    ' for job 'a1e510ad-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 3931313793733241088: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3931313793733241088
    ' for job 'a4ee320d-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 222749343414443648: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 222749343414443648
    ' for job 'a6a16052-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 220989197096055040: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 220989197096055040
    ' for job 'a902cfff-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 4021566209266336640: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 4021566209266336640
    ' for job 'ac8ce130-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 5717278911884264576: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 5717278911884264576
    ' for job 'ae51c2b5-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 2871730758921709952: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 2871730758921709952
    ' for job 'b0c2e9cd-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 5402903764121955840: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 5402903764121955840
    ' for job 'b508a9df-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 3195919254111314816: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3195919254111314816
    ' for job 'b7e738c6-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 1600882199829338368: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1600882199829338368
    ' for job 'ba48815b-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

25/261
failed for 946030529073022080: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 946030529073022080
    ' for job 'bd465818-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 1379500928055726848: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1379500928055726848
    ' for job 'bfabbf62-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

failed for 975968718869126144: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 975968718869126144
    ' for job 'c1bf3619-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 3098328182579892096: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3098328182579892096
    ' for job 'c46a0ad7-3248-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

failed for 3340477717172813568: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3340477717172813568
    ' for job 'c6ac32b1-3248-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !

In [76]:
df

,source_paper,star_name,normalized_name,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days,query_name,simbad_found,simbad_main_id,...,pmra,pmdec,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,bp_rp,ruwe,ebpminrp_gspphot,g_rp,bp_rp_0
0,Engle_2023,L266-195,L266-195,2.50,0.93,1.82,23.19,L266-195,True,L 266-195,...,19.540099,65.965484,10.955764,11.769478,10.074646,1.694832,0.796916,NaN,0.881118,NaN
1,Engle_2023,LP 856-54,LP 856-54,2.52,0.61,1.58,23.27,LP 856-54,True,L 619-49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Engle_2023,G59-39,G59-39,3.20,0.93,1.96,33.82,G59-39,True,G 59-39,...,-354.722430,149.310000,12.777390,13.775156,11.784307,1.990849,1.223360,NaN,0.993083,NaN
3,Engle_2023,LP 775-52,LP 775-52,3.39,0.20,0.29,36.90,LP 775-52,True,LP 775-52,...,267.445870,-171.730706,11.713509,12.747372,10.687969,2.059402,2.017660,NaN,1.025539,NaN
4,Engle_2023,GJ 2131 A,GJ 2131 A,3.47,1.69,1.69,34.82,GJ 2131 A,True,G 154-B5A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Engle_2024,GJ 581,GJ 581,NaN,NaN,NaN,147.80,GJ 581,True,BD-07 4003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,Engle_2024,GJ 699,GJ 699,NaN,NaN,NaN,149.50,GJ 699,True,NAME Barnard's star,...,-801.550978,10362.394207,8.193974,9.791788,6.958091,2.833697,1.084851,0.0,1.235883,2.833697
377,Engle_2024,GJ 273,GJ 273,NaN,NaN,NaN,160.83,GJ 273,True,BD+05 1668,...,571.232347,-3691.486565,8.576388,10.111705,7.353947,2.757758,1.238770,0.0,1.222442,2.757758
378,Engle_2024,LP 855-60,LP 855-60,NaN,NaN,NaN,154.89,LP 855-60,True,LP 855-60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,Engle_2024,GJ 191,GJ 191,NaN,NaN,NaN,153.20,GJ 191,True,HD 33793,...,6491.223339,-5708.614150,8.063552,9.086244,7.059598,2.026646,1.170168,0.0,1.003954,2.026646

In [77]:
failed_ids[:10]

[('6177238671977087360',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ra,\n        dec,\n        parallax,\n        parallax_error,\n        pmra,\n        pmdec,\n        phot_g_mean_mag,\n        phot_bp_mean_mag,\n        phot_rp_mean_mag,\n        bp_rp,\n        ruwe\n    FROM gaiadr3.gaia_source\n    WHERE source_id = 6177238671977087360\n    \' for job \'91449ff9-3248-11f1-9054-bc97e148b76b-O\': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !\n - Unknown table "gaiadr3.gaia_source" !\n - Unknown column "source_id" !\n - Unknown column "ra" !\n - Unknown column "dec" !\n - Unknown column "parallax" !\n - Unknown column "parallax_error" !\n - Unknown column "pmra" !\n - Unknown column "pmdec" !\n - Unknown column "phot_g_mean_mag" !\n - Unknown column "phot_bp_mean_mag" !\n - Unknown column "phot_rp_mean_mag" !\n - Unknown column "bp_rp" !\n - Unknown column "ruwe" !\n - Unknown column "source_id" !\n'),
 ('3930922058356114432',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 3930922058356114432\n    \' for job \'938679b0-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n'),
 ('4149820284980989184',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ra,\n        dec,\n        parallax,\n        parallax_error,\n        pmra,\n        pmdec,\n        phot_g_mean_mag,\n        phot_bp_mean_mag,\n        phot_rp_mean_mag,\n        bp_rp,\n        ruwe\n    FROM gaiadr3.gaia_source\n    WHERE source_id = 4149820284980989184\n    \' for job \'967498ff-3248-11f1-9054-bc97e148b76b-O\': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !\n - Unknown table "gaiadr3.gaia_source" !\n - Unknown column "source_id" !\n - Unknown column "ra" !\n - Unknown column "dec" !\n - Unknown column "parallax" !\n - Unknown column "parallax_error" !\n - Unknown column "pmra" !\n - Unknown column "pmdec" !\n - Unknown column "phot_g_mean_mag" !\n - Unknown column "phot_bp_mean_mag" !\n - Unknown column "phot_rp_mean_mag" !\n - Unknown column "bp_rp" !\n - Unknown column "ruwe" !\n - Unknown column "source_id" !\n'),
 ('661794060190112000',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ra,\n        dec,\n        parallax,\n        parallax_error,\n        pmra,\n        pmdec,\n        phot_g_mean_mag,\n        phot_bp_mean_mag,\n        phot_rp_mean_mag,\n        bp_rp,\n        ruwe\n    FROM gaiadr3.gaia_source\n    WHERE source_id = 661794060190112000\n    \' for job \'98e59910-3248-11f1-9054-bc97e148b76b-O\': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !\n - Unknown table "gaiadr3.gaia_source" !\n - Unknown column "source_id" !\n - Unknown column "ra" !\n - Unknown column "dec" !\n - Unknown column "parallax" !\n - Unknown column "parallax_error" !\n - Unknown column "pmra" !\n - Unknown column "pmdec" !\n - Unknown column "phot_g_mean_mag" !\n - Unknown column "phot_bp_mean_mag" !\n - Unknown column "phot_rp_mean_mag" !\n - Unknown column "bp_rp" !\n - Unknown column "ruwe" !\n - Unknown column "source_id" !\n'),
 ('2485305370114328576',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 2485305370114328576\n    \' for job \'9abcca15-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n'),
 ('1130450270073924608',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 1130450270073924608\n    \' for job \'9d0c1150-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n'),
 ('577602496345490176',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 577602496345490176\n    \' for job \'9f9cce58-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n'),
 ('6885776098199761024',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 6885776098199761024\n    \' for job \'a1e510ad-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n'),
 ('3931313793733241088',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ra,\n        dec,\n        parallax,\n        parallax_error,\n        pmra,\n        pmdec,\n        phot_g_mean_mag,\n        phot_bp_mean_mag,\n        phot_rp_mean_mag,\n        bp_rp,\n        ruwe\n    FROM gaiadr3.gaia_source\n    WHERE source_id = 3931313793733241088\n    \' for job \'a4ee320d-3248-11f1-9054-bc97e148b76b-O\': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !\n - Unknown table "gaiadr3.gaia_source" !\n - Unknown column "source_id" !\n - Unknown column "ra" !\n - Unknown column "dec" !\n - Unknown column "parallax" !\n - Unknown column "parallax_error" !\n - Unknown column "pmra" !\n - Unknown column "pmdec" !\n - Unknown column "phot_g_mean_mag" !\n - Unknown column "phot_bp_mean_mag" !\n - Unknown column "phot_rp_mean_mag" !\n - Unknown column "bp_rp" !\n - Unknown column "ruwe" !\n - Unknown column "source_id" !\n'),
 ('222749343414443648',
  'Error 400: \nCannot parse query \'\n    SELECT\n TOP 2000         source_id,\n        ebpminrp_gspphot\n    FROM gaiadr3.astrophysical_parameters\n    WHERE source_id = 222749343414443648\n    \' for job \'a6a16052-3248-11f1-9054-bc97e148b76b-O\': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !\n - Unknown table "gaiadr3.astrophysical_parameters" !\n - Unknown column "source_id" !\n - Unknown column "ebpminrp_gspphot" !\n - Unknown column "source_id" !\n')]

In [78]:
matched_in_gaia_direct = df["gaia_dr3_source_id_from_simbad"].astype("string").isin(
    gaia_direct["source_id"].astype("string")
).sum()

matched_in_gaia_direct

np.int64(237)

In [79]:
expected_ids = set(
    df["gaia_dr3_source_id_from_simbad"]
    .dropna()
    .astype(str)
    .unique()
)

retrieved_ids = set(
    gaia_direct["source_id"]
    .dropna()
    .astype(str)
    .unique()
)

failed_direct_ids = sorted(expected_ids - retrieved_ids)

len(expected_ids), len(retrieved_ids), len(failed_direct_ids)

(261, 188, 73)

In [80]:
failed_direct_df = df[
    df["gaia_dr3_source_id_from_simbad"].astype("string").isin(failed_direct_ids)
].copy()

failed_direct_df[[
    "star_name",
    "simbad_main_id",
    "gaia_dr3_source_id_from_simbad",
    "simbad_ra_deg",
    "simbad_dec_deg"
]].head(30)

,star_name,simbad_main_id,gaia_dr3_source_id_from_simbad,simbad_ra_deg,simbad_dec_deg
1,LP 856-54,L 619-49,6177238671977087360,207.846787,-27.564567
4,GJ 2131 A,G 154-B5A,4149820284980989184,266.472296,-13.306205
6,HIP 43232 B,UCAC3 222-97968,661794060190112000,132.103835,20.705235
10,GJ 821,Wolf 918,6885776098199761024,317.322613,-13.302504
13,LHS 173,Ross 34,222749343414443648,52.221421,37.382447
23,40 Eri C,* omi02 Eri C,3195919254111314816,63.839733,-7.655748
27,2MASS J23095781+5506472,G 233-42,1996725077535282944,347.491082,55.113161
29,LHS 229,G 107-69,975968718869126144,112.678243,48.199608
31,GJ 213,Ross 47,3340477717172813568,85.538615,12.489335
35,GJ 581,BD-07 4003,6322070093095493504,229.861779,-7.722275
39,LHS 3382,LP 24-219,2269520028411874816,275.470655,77.158340
44,1RXS J030708.3+323528,2MASS J03070968+3235204,135885416558354048,46.790377,32.588959
50,LP 152-39,LP 152-39,356764413385350144,29.556879,48.738837
54,1RXS J085922.2+403351,1RXS J085922.2+403351,720454586079843840,134.840651,40.563066
58,EPIC 206349327,BPS CS 22886-0057,2622525894434166272,335.100785,-7.459508
60,G 173-18,G 173-18,351045720262686080,26.325883,46.535509
73,UCAC4 678-130516,PM J23116+4532,1941126622803033984,347.911438,45.540416
77,1RXS J051125.0+265849,ZTF J051126.17+265845.8,3421775057173721600,77.859095,26.979467
82,CK Ari,V* CK Ari,117990177621007744,51.809763,27.385743
85,TYC 3483-856-1,RX J1532.6+4653,1401005829306968064,233.155675,46.884665
87,EPIC 210707811,HG 7-152,47729215646206080,64.460973,18.475190
89,V2689 Ori,V* V2689 Ori,3339921875389105152,84.129127,11.327869
97,StKM 1-1407,StKM 1-1407,1308058064097405696,252.780417,28.600304
99,GJ 685,G 226-66,1439069444391326208,263.893661,61.681563
109,GJ 2,BD+44 4548,386655019234959872,1.295372,45.786567
111,GJ 47,Wolf 44,426641955043723520,15.333538,61.365745
114,GJ 832,HD 204961,6562924609150908416,323.391563,-49.009000
117,BD-18 359,BD-18 359,5138510181584617856,31.270329,-17.614649
123,GJ 476,Wolf 427,3903318372263850368,188.752939,9.828490
127,GJ 433,CD-31 9113,3478160727866058368,173.862282,-32.539968

In [81]:
failed_direct_df.to_csv("engle_failed_direct_gaia_ids.csv", index=False)

In [82]:
succeeded_direct_ids = sorted(expected_ids & retrieved_ids)

succeeded_direct_df = df[
    df["gaia_dr3_source_id_from_simbad"].astype("string").isin(succeeded_direct_ids)
].copy()

len(succeeded_direct_df)

237

In [83]:
retry_core_rows = []
retry_ap_rows = []
retry_failures = []

for i, sid in enumerate(failed_direct_ids, start=1):
    print(f"{i}/{len(failed_direct_ids)} : {sid}")
    try:
        c = query_gaia_one_source_id(sid)
        if len(c) > 0:
            retry_core_rows.append(c)

        a = query_ap_one_source_id(sid)
        if len(a) > 0:
            retry_ap_rows.append(a)

    except Exception as e:
        retry_failures.append((sid, str(e)))
        print(f"failed again for {sid}: {e}")

1/73 : 1071195187567668480
2/73 : 1149897160435827200
failed again for 1149897160435827200: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1149897160435827200
    ' for job 'ecf6fcb4-3252-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

3/73 : 117990177621007744
4/73 : 119736889281099136
failed again for 119736889281099136: 70:0: no element found
5/73 : 1214160733157163008
6/73 : 1229089524081628416
failed again for 1229089524081628416: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1229089524081628416
    ' for job 'f264e91a-3252-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

7/73 : 1308058064097405696
8/73 : 1310513342280948480
failed again for 1310513342280948480: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1310513342280948480
    ' for job 'f67bd0fc-3252-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

9/73 : 135885416558354048
10/73 : 1363678268537372544
failed again for 1363678268537372544: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1363678268537372544
    ' for job 'f8fc8875-3252-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

11/73 : 1401005829306968064
failed again for 1401005829306968064: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1401005829306968064
    ' for job 'faba8c29-3252-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

12/73 : 1439069444391326208
failed again for 1439069444391326208: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1439069444391326208
    ' for job 'fd335465-3252-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

13/73 : 1495487688115551744
failed again for 1495487688115551744: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1495487688115551744
    ' for job 'ff65017d-3252-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

14/73 : 170712584810347904
15/73 : 1803475188714186368
failed again for 1803475188714186368: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1803475188714186368
    ' for job '02ef39bb-3253-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

16/73 : 1810616448010879488
failed again for 1810616448010879488: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1810616448010879488
    ' for job '04d36310-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

17/73 : 1941126622803033984
failed again for 1941126622803033984: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1941126622803033984
    ' for job '07382e18-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

18/73 : 1992715605301433856
failed again for 1992715605301433856: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 1992715605301433856
    ' for job '09885fb0-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

19/73 : 1996725077535282944
failed again for 1996725077535282944: 70:0: no element found
20/73 : 222749343414443648
failed again for 222749343414443648: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 222749343414443648
    ' for job '0e49df72-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

21/73 : 2269520028411874816
failed again for 2269520028411874816: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 2269520028411874816
    ' for job '10bb2d9c-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

22/73 : 2384348242516852864
23/73 : 2595284016771502080
failed again for 2595284016771502080: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 2595284016771502080
    ' for job '13b8b63e-3253-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

24/73 : 2603090003484152064
25/73 : 2622525894434166272
26/73 : 2640434056928150400
27/73 : 2828928008202069376
28/73 : 2855743172658367360
29/73 : 2918040883015489408
30/73 : 2940856402123426176
31/73 : 3179036008830848
failed again for 3179036008830848: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3179036008830848
    ' for job '22619ca7-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

32/73 : 3187115498866675456
33/73 : 3195919254111314816
failed again for 3195919254111314816: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3195919254111314816
    ' for job '26c3974c-3253-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

34/73 : 3339921875389105152
35/73 : 3340477717172813568
failed again for 3340477717172813568: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3340477717172813568
    ' for job '29b1b69c-3253-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

36/73 : 3421775057173721600
failed again for 3421775057173721600: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3421775057173721600
    ' for job '2b9543b3-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

37/73 : 3478160727866058368
failed again for 3478160727866058368: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3478160727866058368
    ' for job '2de7711b-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

38/73 : 3492638237986110080
failed again for 3492638237986110080: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 3492638237986110080
    ' for job '3103cc59-3253-11f1-9054-bc97e148b76b-O': 4 unresolved identifiers: astrophysical_parameters [l.5 c.10 - l.5 c.42], source_id [l.3 c.19 - l.3 c.28], ebpminrp_gspphot [l.4 c.9 - l.4 c.25], source_id [l.6 c.11 - l.6 c.20] !
 - Unknown table "gaiadr3.astrophysical_parameters" !
 - Unknown column "source_id" !
 - Unknown column "ebpminrp_gspphot" !
 - Unknown column "source_id" !

39/73 : 351045720262686080
failed again for 351045720262686080: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ebpminrp_gspphot
    FROM gaiadr3.astrophysical_parameters
    WHERE source_id = 351045720262686080

In [84]:
retry_core = pd.concat(retry_core_rows, ignore_index=True) if retry_core_rows else pd.DataFrame()
retry_ap = pd.concat(retry_ap_rows, ignore_index=True) if retry_ap_rows else pd.DataFrame()

retry_direct = retry_core.merge(retry_ap, how="left", on="source_id")
retry_direct["g_rp"] = retry_direct["phot_g_mean_mag"] - retry_direct["phot_rp_mean_mag"]
retry_direct["bp_rp_0"] = retry_direct["bp_rp"] - retry_direct["ebpminrp_gspphot"]

In [85]:
gaia_direct = pd.concat([gaia_direct, retry_direct], ignore_index=True)
gaia_direct = gaia_direct.drop_duplicates(subset="source_id", keep="first")

In [86]:
retrieved_ids = set(gaia_direct["source_id"].dropna().astype(str).unique())
failed_direct_ids = sorted(expected_ids - retrieved_ids)

len(retrieved_ids), len(failed_direct_ids)

(239, 22)

In [87]:
df["gaia_dr3_source_id_from_simbad"] = df["gaia_dr3_source_id_from_simbad"].astype("string")
gaia_direct["source_id"] = gaia_direct["source_id"].astype("string")

df_direct = df.merge(
    gaia_direct,
    how="left",
    left_on="gaia_dr3_source_id_from_simbad",
    right_on="source_id"
)

df_direct.to_csv("engle_direct_gaia_progress.csv", index=False)

In [88]:
still_failed_direct_df = df[
    df["gaia_dr3_source_id_from_simbad"].astype("string").isin(failed_direct_ids)
].copy()

still_failed_direct_df[[
    "star_name",
    "simbad_main_id",
    "gaia_dr3_source_id_from_simbad",
    "simbad_ra_deg",
    "simbad_dec_deg"
]].head(30)

,star_name,simbad_main_id,gaia_dr3_source_id_from_simbad,simbad_ra_deg,simbad_dec_deg
4,GJ 2131 A,G 154-B5A,4149820284980989184,266.472296,-13.306205
23,40 Eri C,* omi02 Eri C,3195919254111314816,63.839733,-7.655748
27,2MASS J23095781+5506472,G 233-42,1996725077535282944,347.491082,55.113161
29,LHS 229,G 107-69,975968718869126144,112.678243,48.199608
31,GJ 213,Ross 47,3340477717172813568,85.538615,12.489335
109,GJ 2,BD+44 4548,386655019234959872,1.295372,45.786567
111,GJ 47,Wolf 44,426641955043723520,15.333538,61.365745
114,GJ 832,HD 204961,6562924609150908416,323.391563,-49.009000
117,BD-18 359,BD-18 359,5138510181584617856,31.270329,-17.614649
140,HAT 214-03527,2MASS J03303120+2844185,119736889281099136,52.629976,28.738439
146,G 176-13,G 176-13,778671836983753088,166.519764,42.880407
156,LP 331-57A,LP 331-57 A,1310513342280948480,255.970197,32.196126
172,1RXS J174158.2+475403,ATO J265.4903+47.8980,1363678268537372544,265.490175,47.898439
174,2MASS J06170531+8353354,LSPM J0617+8353,1149897160435827200,94.271939,83.893188
184,2MASS J13505181+3644168,Ross 1019,1495487688115551744,207.715673,36.738098
209,au Mic,HD 197481,6794047652729201024,311.289719,-31.340899
211,GJ 410,V* DS Leo,3988689609004982912,165.659758,21.967139
217,GJ 832,HD 204961,6562924609150908416,323.391563,-49.009000
238,GJ 1132,L 320-124,5413438219396893568,153.715745,-47.156720
248,GJ 803,HD 197481,6794047652729201024,311.289719,-31.340899
264,GJ 2,BD+44 4548,386655019234959872,1.295372,45.786567
279,GJ 3998,BD+11 3149,4540061704989418240,259.002654,11.057671
283,GJ 47,Wolf 44,426641955043723520,15.333538,61.365745
284,GJ 9689,Ross 754,1803475188714186368,303.465864,13.388810
288,GJ 832,HD 204961,6562924609150908416,323.391563,-49.009000
300,GJ 536,HD 122303,3657653114880309248,210.263284,-2.654867
322,GJ 4274,L 788-34,2595284016771502080,335.779153,-17.607315
335,GJ 832,HD 204961,6562924609150908416,323.391563,-49.009000

In [89]:
still_failed_direct_df[[
    "star_name",
    "simbad_main_id",
    "gaia_dr3_source_id_from_simbad"
]].drop_duplicates().sort_values("star_name")

,star_name,simbad_main_id,gaia_dr3_source_id_from_simbad
172,1RXS J174158.2+475403,ATO J265.4903+47.8980,1363678268537372544
174,2MASS J06170531+8353354,LSPM J0617+8353,1149897160435827200
184,2MASS J13505181+3644168,Ross 1019,1495487688115551744
27,2MASS J23095781+5506472,G 233-42,1996725077535282944
23,40 Eri C,* omi02 Eri C,3195919254111314816
117,BD-18 359,BD-18 359,5138510181584617856
146,G 176-13,G 176-13,778671836983753088
238,GJ 1132,L 320-124,5413438219396893568
109,GJ 2,BD+44 4548,386655019234959872
31,GJ 213,Ross 47,3340477717172813568
4,GJ 2131 A,G 154-B5A,4149820284980989184
279,GJ 3998,BD+11 3149,4540061704989418240
211,GJ 410,V* DS Leo,3988689609004982912
322,GJ 4274,L 788-34,2595284016771502080
111,GJ 47,Wolf 44,426641955043723520
300,GJ 536,HD 122303,3657653114880309248
248,GJ 803,HD 197481,6794047652729201024
114,GJ 832,HD 204961,6562924609150908416
284,GJ 9689,Ross 754,1803475188714186368
140,HAT 214-03527,2MASS J03303120+2844185,119736889281099136
29,LHS 229,G 107-69,975968718869126144
156,LP 331-57A,LP 331-57 A,1310513342280948480
209,au Mic,HD 197481,6794047652729201024

In [92]:
retry_ids = (
    still_failed_direct_df["gaia_dr3_source_id_from_simbad"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

len(retry_ids), retry_ids[:10]

(22,
 ['4149820284980989184',
  '3195919254111314816',
  '1996725077535282944',
  '975968718869126144',
  '3340477717172813568',
  '386655019234959872',
  '426641955043723520',
  '6562924609150908416',
  '5138510181584617856',
  '119736889281099136'])

In [95]:
import time
import pandas as pd

retry2_core_rows = []
retry2_ap_rows = []
retry2_failures = []

for i, sid in enumerate(retry_ids, start=1):
    print(f"{i}/{len(retry_ids)} : {sid}")

    try:
        c = query_gaia_one_source_id(sid)
        if len(c) > 0:
            retry2_core_rows.append(c)

        a = query_ap_one_source_id(sid)
        if len(a) > 0:
            retry2_ap_rows.append(a)

        time.sleep(1.0)

    except Exception as e:
        retry2_failures.append((sid, str(e)))
        print(f"failed again for {sid}: {e}")
        time.sleep(2.0)

1/22 : 4149820284980989184
failed again for 4149820284980989184: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 4149820284980989184
    ' for job '6e37e250-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

2/22 : 3195919254111314816
failed again for 3195919254111314816: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 3195919254111314816
    ' for job '70e771fa-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

3/22 : 1996725077535282944
failed again for 1996725077535282944: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1996725077535282944
    ' for job '73489382-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

4/22 : 975968718869126144
failed again for 975968718869126144: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 975968718869126144
    ' for job '75aa2a3b-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

5/22 : 3340477717172813568
6/22 : 386655019234959872
failed again for 386655019234959872: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 386655019234959872
    ' for job '79efea4a-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

7/22 : 426641955043723520
failed again for 426641955043723520: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 426641955043723520
    ' for job '7d6a6b12-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

8/22 : 6562924609150908416
failed again for 6562924609150908416: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 6562924609150908416
    ' for job '8008206b-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

9/22 : 5138510181584617856
failed again for 5138510181584617856: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 5138510181584617856
    ' for job '822d4a63-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

10/22 : 119736889281099136
failed again for 119736889281099136: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 119736889281099136
    ' for job '848f7d5a-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

11/22 : 778671836983753088
failed again for 778671836983753088: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 778671836983753088
    ' for job '86f029b5-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

12/22 : 1310513342280948480
failed again for 1310513342280948480: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1310513342280948480
    ' for job '8951c06f-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

13/22 : 1363678268537372544
failed again for 1363678268537372544: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1363678268537372544
    ' for job '8bb2bae5-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

14/22 : 1149897160435827200
failed again for 1149897160435827200: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1149897160435827200
    ' for job '8e142a8f-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

15/22 : 1495487688115551744
failed again for 1495487688115551744: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,
        ruwe
    FROM gaiadr3.gaia_source
    WHERE source_id = 1495487688115551744
    ' for job '90852a96-3254-11f1-9054-bc97e148b76b-O': 14 unresolved identifiers: gaia_source [l.15 c.10 - l.15 c.29], source_id [l.3 c.19 - l.3 c.28], ra [l.4 c.9 - l.4 c.11], dec [l.5 c.9 - l.5 c.12], parallax [l.6 c.9 - l.6 c.17], parallax_error [l.7 c.9 - l.7 c.23], pmra [l.8 c.9 - l.8 c.13], pmdec [l.9 c.9 - l.9 c.14], phot_g_mean_mag [l.10 c.9 - l.10 c.24], phot_bp_mean_mag [l.11 c.9 - l.11 c.25], phot_rp_mean_mag [l.12 c.9 - l.12 c.25], bp_rp [l.13 c.9 - l.13 c.14], ruwe [l.14 c.9 - l.14 c.13], source_id [l.16 c.11 - l.16 c.20] !
 - Unknown table "gaiadr3.gaia_source" !
 - Unknown column "source_id" !
 - Unknown column "ra" !
 - Unknown column "dec" !
 - Unknown column "parallax" !
 - Unknown column "parallax_error" !
 - Unknown column "pmra" !
 - Unknown column "pmdec" !
 - Unknown column "phot_g_mean_mag" !
 - Unknown column "phot_bp_mean_mag" !
 - Unknown column "phot_rp_mean_mag" !
 - Unknown column "bp_rp" !
 - Unknown column "ruwe" !
 - Unknown column "source_id" !

16/22 : 6794047652729201024
failed again for 6794047652729201024: Error 400:
Cannot parse query '
    SELECT
 TOP 2000         source_id,
        ra,
        dec,
        parallax,
        parallax_error,
        pmra,
        pmdec,
        phot_g_mean_mag,
        phot_bp_mean_mag,
        phot_rp_mean_mag,
        bp_rp,

In [96]:
retry2_core = pd.concat(retry2_core_rows, ignore_index=True) if retry2_core_rows else pd.DataFrame()
retry2_ap = pd.concat(retry2_ap_rows, ignore_index=True) if retry2_ap_rows else pd.DataFrame()

if len(retry2_core) > 0:
    retry2_direct = retry2_core.merge(retry2_ap, how="left", on="source_id")
    retry2_direct["g_rp"] = retry2_direct["phot_g_mean_mag"] - retry2_direct["phot_rp_mean_mag"]
    retry2_direct["bp_rp_0"] = retry2_direct["bp_rp"] - retry2_direct["ebpminrp_gspphot"]

    gaia_direct = pd.concat([gaia_direct, retry2_direct], ignore_index=True)
    gaia_direct = gaia_direct.drop_duplicates(subset="source_id", keep="first")

In [97]:
retrieved_ids = set(gaia_direct["source_id"].dropna().astype(str).unique())

still_failed_direct_df = df[
    df["gaia_dr3_source_id_from_simbad"].astype("string").isin(
        sorted(expected_ids - retrieved_ids)
    )
].copy()

len(still_failed_direct_df)

26

In [98]:
df

,source_paper,star_name,normalized_name,age_gyr,age_err_lo_gyr,age_err_hi_gyr,prot_days,query_name,simbad_found,simbad_main_id,...,pmra,pmdec,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,bp_rp,ruwe,ebpminrp_gspphot,g_rp,bp_rp_0
0,Engle_2023,L266-195,L266-195,2.50,0.93,1.82,23.19,L266-195,True,L 266-195,...,19.540099,65.965484,10.955764,11.769478,10.074646,1.694832,0.796916,NaN,0.881118,NaN
1,Engle_2023,LP 856-54,LP 856-54,2.52,0.61,1.58,23.27,LP 856-54,True,L 619-49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Engle_2023,G59-39,G59-39,3.20,0.93,1.96,33.82,G59-39,True,G 59-39,...,-354.722430,149.310000,12.777390,13.775156,11.784307,1.990849,1.223360,NaN,0.993083,NaN
3,Engle_2023,LP 775-52,LP 775-52,3.39,0.20,0.29,36.90,LP 775-52,True,LP 775-52,...,267.445870,-171.730706,11.713509,12.747372,10.687969,2.059402,2.017660,NaN,1.025539,NaN
4,Engle_2023,GJ 2131 A,GJ 2131 A,3.47,1.69,1.69,34.82,GJ 2131 A,True,G 154-B5A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Engle_2024,GJ 581,GJ 581,NaN,NaN,NaN,147.80,GJ 581,True,BD-07 4003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,Engle_2024,GJ 699,GJ 699,NaN,NaN,NaN,149.50,GJ 699,True,NAME Barnard's star,...,-801.550978,10362.394207,8.193974,9.791788,6.958091,2.833697,1.084851,0.0,1.235883,2.833697
377,Engle_2024,GJ 273,GJ 273,NaN,NaN,NaN,160.83,GJ 273,True,BD+05 1668,...,571.232347,-3691.486565,8.576388,10.111705,7.353947,2.757758,1.238770,0.0,1.222442,2.757758
378,Engle_2024,LP 855-60,LP 855-60,NaN,NaN,NaN,154.89,LP 855-60,True,LP 855-60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,Engle_2024,GJ 191,GJ 191,NaN,NaN,NaN,153.20,GJ 191,True,HD 33793,...,6491.223339,-5708.614150,8.063552,9.086244,7.059598,2.026646,1.170168,0.0,1.003954,2.026646

## Cone search fallback + final assembly

Load the intermediate save (stable base after all direct queries), then apply a 5-arcsec cone search for every row still missing a Gaia `source_id` but with known SIMBAD coordinates. Finally add the RUWE quality flag and export.

In [2]:
# Load from the best available output (346/380 matched from previous run).
df_final = pd.read_csv(
    "cf_data/engle_gaia_xmatch.csv",
    dtype={"gaia_dr3_source_id_from_simbad": "string", "source_id": "string"}
)
print(f"Total rows:          {len(df_final)}")
print(f"With Gaia source_id: {df_final['source_id'].notna().sum()}")
print(f"Missing Gaia data:   {df_final['source_id'].isna().sum()}")

Total rows:          380
With Gaia source_id: 346
Missing Gaia data:   34

In [3]:
# Split missing stars into two groups:
#   1. Known Gaia ID (from SIMBAD) but direct query failed → retry by ID
#   2. No Gaia ID → cone search by SIMBAD coordinates
missing_mask = df_final["source_id"].isna()

retry_direct = df_final[
    missing_mask &
    df_final["gaia_dr3_source_id_from_simbad"].notna()
].drop_duplicates(subset=["gaia_dr3_source_id_from_simbad"])

needs_cone = df_final[
    missing_mask &
    df_final["gaia_dr3_source_id_from_simbad"].isna() &
    df_final["simbad_ra_deg"].notna()
].drop_duplicates(subset=["simbad_ra_deg", "simbad_dec_deg"])

print(f"Have Gaia ID, direct query failed → retry: {len(retry_direct)}")
print(f"No Gaia ID, have SIMBAD coords → cone search: {len(needs_cone)}")
print(f"No SIMBAD match at all (unrecoverable): {df_final[missing_mask & df_final['simbad_ra_deg'].isna()]['star_name'].nunique()}")

Have Gaia ID, direct query failed → retry: 26
No Gaia ID, have SIMBAD coords → cone search: 3
No SIMBAD match at all (unrecoverable): 3

In [4]:
import time

# Step 1: retry direct Gaia query by source_id for the 73 stars
# whose IDs we already know from SIMBAD (previous attempts hit API errors).
retry_core_rows = []
retry_ap_rows   = []
retry_id_failures = []

for i, row in enumerate(retry_direct.itertuples(), start=1):
    sid = str(row.gaia_dr3_source_id_from_simbad)
    print(f"{i}/{len(retry_direct)}: {row.star_name}  (id={sid})")
    try:
        c = query_gaia_one_source_id(sid)
        if len(c) > 0:
            retry_core_rows.append(c)
        a = query_ap_one_source_id(sid)
        if len(a) > 0:
            retry_ap_rows.append(a)
        time.sleep(1.0)
    except Exception as e:
        retry_id_failures.append({"star_name": row.star_name, "source_id": sid, "reason": str(e)})
        print(f"  -> ERROR: {e}")
        time.sleep(2.0)

print(f"\nDirect retry: {len(retry_core_rows)} recovered, {len(retry_id_failures)} still failing")

1/26: GJ 2131 A  (id=4149820284980989184)

2/26: 40 Eri C  (id=3195919254111314816)

3/26: 2MASS J23095781+5506472  (id=1996725077535282944)

4/26: LHS 229  (id=975968718869126144)

5/26: GJ 213  (id=3340477717172813568)

6/26: GJ 2  (id=386655019234959872)

7/26: GJ 47  (id=426641955043723520)

8/26: GJ 832  (id=6562924609150908416)

9/26: BD-18 359  (id=5138510181584617856)

10/26: HAT 214-03527  (id=119736889281099136)

11/26: G 176-13  (id=778671836983753088)

12/26: LP 331-57A  (id=1310513342280948480)

13/26: 1RXS J174158.2+475403  (id=1363678268537372544)

14/26: 2MASS J06170531+8353354  (id=1149897160435827200)

15/26: 2MASS J13505181+3644168  (id=1495487688115551744)

16/26: au Mic  (id=6794047652729201024)

17/26: GJ 410  (id=3988689609004982912)

18/26: GJ 832  (id=6.562924609150908e+18)

19/26: GJ 1132  (id=5413438219396893568)

20/26: GJ 803  (id=6.794047652729201e+18)

21/26: GJ 2  (id=3.866550192349599e+17)

22/26: GJ 3998  (id=4540061704989418240)

23/26: GJ 47  (id=4.266419550437235e+17)

24/26: GJ 9689  (id=1803475188714186368)

25/26: GJ 536  (id=3657653114880309248)

26/26: GJ 4274  (id=2595284016771502080)

Direct retry: 22 recovered, 0 still failing

In [5]:
# Assemble direct retry results and fill into df_final.
if retry_core_rows:
    retry_core = pd.concat(retry_core_rows, ignore_index=True)
    retry_ap   = pd.concat(retry_ap_rows, ignore_index=True) if retry_ap_rows else pd.DataFrame()

    if len(retry_ap) > 0:
        retry_gaia = retry_core.merge(retry_ap, how="left", on="source_id")
    else:
        retry_gaia = retry_core.copy()

    retry_gaia["g_rp"]    = retry_gaia["phot_g_mean_mag"] - retry_gaia["phot_rp_mean_mag"]
    retry_gaia["bp_rp_0"] = retry_gaia["bp_rp"] - retry_gaia["ebpminrp_gspphot"]
    # Keep source_id as plain Python str for reliable lookup
    retry_gaia["source_id_str"] = retry_gaia["source_id"].apply(lambda x: str(int(x)))
    retry_lookup = retry_gaia.set_index("source_id_str")

    gaia_fill_cols = [
        "source_id", "ra", "dec", "parallax", "parallax_error",
        "pmra", "pmdec", "phot_g_mean_mag", "phot_bp_mean_mag",
        "phot_rp_mean_mag", "bp_rp", "g_rp", "ruwe", "ebpminrp_gspphot", "bp_rp_0"
    ]

    # re-extract clean IDs from simbad_ids for matching
    import re as _re
    def _clean_id(ids_str):
        if not isinstance(ids_str, str): return None
        m = _re.search(r"Gaia DR3\s+(\d+)", ids_str)
        return m.group(1) if m else None

    mask = df_final["source_id"].isna() & df_final["simbad_ids"].notna()
    filled = 0
    for idx, row in df_final[mask].iterrows():
        cid = _clean_id(row["simbad_ids"])
        if cid and cid in retry_lookup.index:
            gr = retry_lookup.loc[cid]
            if isinstance(gr, pd.DataFrame): gr = gr.iloc[0]
            for col in gaia_fill_cols:
                if col in gr.index:
                    df_final.at[idx, col] = gr[col]
            df_final.at[idx, "gaia_dr3_source_id_from_simbad"] = cid
            filled += 1
    print(f"Filled {filled} rows from direct retry")
else:
    print("No direct retry results.")

print(f"After direct retry fill:")
print(f"  With Gaia source_id: {df_final['source_id'].notna().sum()}")
print(f"  Still missing:       {df_final['source_id'].isna().sum()}")

TypeError: Invalid value '4.149820284980989e+18' for dtype 'string'. Value should be a string or missing value, got 'float64' instead.

In [ ]:
# Step 2: cone search for stars that have SIMBAD coords but no Gaia ID.
# (These never had a source_id to query directly.)
cone_results  = []
cone_failures = []

for i, row in enumerate(needs_cone.itertuples(), start=1):
    print(f"{i}/{len(needs_cone)}: {row.star_name}")
    try:
        candidates = gaia_cone_search(row.simbad_ra_deg, row.simbad_dec_deg, radius_arcsec=5)
        best, flag = choose_best_gaia_match(candidates)
        if best is not None:
            best["simbad_ra_deg"] = row.simbad_ra_deg
            best["simbad_dec_deg"] = row.simbad_dec_deg
            best["cone_flag"] = flag
            cone_results.append(best)
            print(f"  -> matched source_id={best['source_id']}, dist={best['dist_arcsec']:.2f}'")
        else:
            cone_failures.append({"star_name": row.star_name, "reason": flag})
            print(f"  -> no match ({flag})")
        time.sleep(0.5)
    except Exception as e:
        cone_failures.append({"star_name": row.star_name, "reason": str(e)})
        print(f"  -> ERROR: {e}")
        time.sleep(2.0)

print(f"\nCone search matched: {len(cone_results)}")
print(f"Still unmatched:     {len(cone_failures)}")

In [ ]:
# Inspect cone results before merging
if cone_results:
    cone_df = pd.DataFrame(cone_results)
    cone_df["source_id"] = cone_df["source_id"].astype("string")
    cone_df["g_rp"]    = cone_df["phot_g_mean_mag"] - cone_df["phot_rp_mean_mag"]
    cone_df["bp_rp_0"] = cone_df["bp_rp"] - cone_df["ebpminrp_gspphot"]
    print(cone_df[["source_id", "dist_arcsec", "parallax", "bp_rp", "ruwe", "cone_flag"]].to_string())
else:
    cone_df = pd.DataFrame()
    print("No cone search results.")

In [ ]:
# Fill df_final rows that were missing source_id with cone search results.
# Match on (simbad_ra_deg, simbad_dec_deg) â€” unique per SIMBAD position.
gaia_fill_cols = [
    "source_id", "ra", "dec", "parallax", "parallax_error",
    "pmra", "pmdec", "phot_g_mean_mag", "phot_bp_mean_mag",
    "phot_rp_mean_mag", "bp_rp", "g_rp", "ruwe",
    "ebpminrp_gspphot", "bp_rp_0"
]

if len(cone_df) > 0:
    cone_lookup = cone_df.set_index(["simbad_ra_deg", "simbad_dec_deg"])
    mask = df_final["source_id"].isna() & df_final["simbad_ra_deg"].notna()
    for idx, row in df_final[mask].iterrows():
        key = (row["simbad_ra_deg"], row["simbad_dec_deg"])
        if key in cone_lookup.index:
            cr = cone_lookup.loc[key]
            if isinstance(cr, pd.DataFrame):
                cr = cr.iloc[0]
            for col in gaia_fill_cols:
                if col in cr.index:
                    df_final.at[idx, col] = cr[col]

print(f"After cone search fill:")
print(f"  With Gaia source_id: {df_final['source_id'].notna().sum()}")
print(f"  Still missing:       {df_final['source_id'].isna().sum()}")

In [ ]:
# Manual overrides for names SIMBAD cannot resolve.
MANUAL_NAME_MAP = {
    "Gaia DR3 75525a": "G 148-7",
}
for bad_name, good_name in MANUAL_NAME_MAP.items():
    mask = (df_final["star_name"] == bad_name) & (df_final["simbad_status"] == "no_result")
    if mask.any():
        df_final.loc[mask, "star_name"] = good_name
        print(f"Renamed {bad_name!r} -> {good_name!r} ({mask.sum()} rows)")
import re as _re2, time

# Retry SIMBAD for stars that never matched — strip parentheticals,
# try the GJ/identifier inside brackets first.
def candidate_names(raw):
    names = []
    m = _re2.search(r'\(([^)]+)\)', raw)
    if m: names.append(m.group(1).strip())
    base = _re2.sub(r'\s*\([^)]*\)', '', raw).strip()
    if base and base != raw: names.append(base)
    names.append(raw.strip())
    seen = set()
    return [n for n in names if not (n in seen or seen.add(n))]

no_simbad = df_final[df_final["simbad_status"] == "no_result"].copy()
print(f"Stars with no SIMBAD match to retry: {len(no_simbad)}")

for i, row in enumerate(no_simbad.itertuples(), start=1):
    candidates = candidate_names(row.star_name)
    print(f"\n{i}/{len(no_simbad)}: '{row.star_name}' -> trying {candidates}")
    sim = None
    for cname in candidates:
        try:
            result = simbad_lookup(cname)
            if result and result.get("simbad_status") == "ok":
                sim = result; break
        except: pass
        time.sleep(0.3)
    if sim is None:
        print(f"  -> still no match"); continue
    print(f"  -> {sim['simbad_main_id']}")
    mask = df_final["star_name"] == row.star_name
    df_final.loc[mask, "simbad_main_id"]  = sim["simbad_main_id"]
    df_final.loc[mask, "simbad_ra_deg"]   = sim["simbad_ra_deg"]
    df_final.loc[mask, "simbad_dec_deg"]  = sim["simbad_dec_deg"]
    df_final.loc[mask, "simbad_ids"]      = sim["simbad_ids"]
    df_final.loc[mask, "simbad_status"]   = "ok"
    gaia_id = extract_gaia_dr3_id(sim["simbad_ids"])
    if not gaia_id:
        print(f"  -> no Gaia ID in SIMBAD"); continue
    df_final.loc[mask, "gaia_dr3_source_id_from_simbad"] = gaia_id
    print(f"  -> Gaia ID {gaia_id}, querying...")
    try:
        c = query_gaia_one_source_id(gaia_id)
        a = query_ap_one_source_id(gaia_id)
        if len(c) > 0:
            gr = c.iloc[0]; ap_val = a.iloc[0]["ebpminrp_gspphot"] if len(a) > 0 else None
            for idx in df_final[mask].index:
                df_final.at[idx, "source_id"]        = str(int(gr["source_id"]))
                df_final.at[idx, "ra"]               = gr["ra"]
                df_final.at[idx, "dec"]              = gr["dec"]
                df_final.at[idx, "parallax"]         = gr["parallax"]
                df_final.at[idx, "parallax_error"]   = gr["parallax_error"]
                df_final.at[idx, "pmra"]             = gr["pmra"]
                df_final.at[idx, "pmdec"]            = gr["pmdec"]
                df_final.at[idx, "phot_g_mean_mag"]  = gr["phot_g_mean_mag"]
                df_final.at[idx, "phot_bp_mean_mag"] = gr["phot_bp_mean_mag"]
                df_final.at[idx, "phot_rp_mean_mag"] = gr["phot_rp_mean_mag"]
                df_final.at[idx, "bp_rp"]            = gr["bp_rp"]
                df_final.at[idx, "g_rp"]             = gr["phot_g_mean_mag"] - gr["phot_rp_mean_mag"]
                df_final.at[idx, "ruwe"]             = gr["ruwe"]
                df_final.at[idx, "ebpminrp_gspphot"] = ap_val
                df_final.at[idx, "bp_rp_0"]          = (gr["bp_rp"] - ap_val) if ap_val is not None else None
            print(f"  -> matched! parallax={gr['parallax']:.1f} mas, G={gr['phot_g_mean_mag']:.2f}")
        time.sleep(1.0)
    except Exception as e:
        print(f"  -> Gaia error: {e}"); time.sleep(2.0)

print(f"\nAfter SIMBAD retry fill:")
print(f"  With Gaia source_id: {df_final['source_id'].notna().sum()}")
print(f"  Still missing:       {df_final['source_id'].isna().sum()}")

In [ ]:
# Add RUWE quality flag (>= 1.2 indicates potential binary/astrometric issue).
# Rows with no Gaia data have NaN RUWE; flag is left None for those.
df_final["ruwe_flag"] = df_final["ruwe"].apply(
    lambda r: (r >= 1.2) if pd.notna(r) else None
)

print(f"RUWE >= 1.2 (flagged): {df_final['ruwe_flag'].eq(True).sum()}")
print(f"RUWE < 1.2 (clean):    {df_final['ruwe_flag'].eq(False).sum()}")
print(f"No RUWE data:          {df_final['ruwe_flag'].isna().sum()}")

In [ ]:
print("=== Final Engle x Gaia DR3 cross-match summary ===")
print(f"Total Engle stars:        {len(df_final)}")
print(f"SIMBAD matched:           {(df_final['simbad_status'] == 'ok').sum()}")
print(f"No SIMBAD match:          {(df_final['simbad_status'] == 'no_result').sum()}")
print(f"With Gaia source_id:      {df_final['source_id'].notna().sum()}")
print(f"With parallax:            {df_final['parallax'].notna().sum()}")
print(f"RUWE flagged (>= 1.2):    {df_final['ruwe_flag'].eq(True).sum()}")
print(f"No Gaia match at all:     {df_final['source_id'].isna().sum()}")

out_path = "cf_data/engle_gaia_xmatch.csv"
df_final.to_csv(out_path, index=False)
print(f"\nSaved to {out_path}")