In [2]:
import numpy as np
import pandas as pd

pass2022 = pd.read_csv("cf_data/pass2022.csv")
pass2022

,name,role,binary_type,system_id,mass_msun,prot_days,age_min_gyr,age_c18_gyr,gaia_source_id,gaia_parallax,gaia_parallax_error,gaia_parallax_over_error,gaia_phot_g_mean_mag,gaia_bp_rp,gaia_ebpminrp_gspphot,gaia_teff_gspphot,gaia_ruwe,flag_multi_match,flag_high_ruwe,bprp0
0,SCR J1107-3420 B,primary,WDM,SCR J1107-3420 B,0.26,7.611,0.64,1.5,5401688460176652288,NaN,NaN,NaN,13.811878,3.135307,NaN,NaN,NaN,False,False,3.135307
1,SCR J1107-3420 A,companion,WDM,SCR J1107-3420 B,NaN,NaN,0.64,1.5,5401688425816913920,38.194987,0.021068,1812.969849,13.699981,-0.085271,NaN,NaN,1.053647,True,False,-0.085271
2,LHS 2928,primary,WDM,LHS 2928,0.25,126.233,5.90,16.9,6272325816233230336,30.928890,0.108796,284.282928,13.776616,2.893877,NaN,NaN,5.506029,False,True,2.893877
3,LHS 2927,companion,WDM,LHS 2928,NaN,NaN,5.90,16.9,6272326022391660544,30.706253,0.107189,286.468964,17.433027,1.156818,NaN,NaN,1.046181,False,False,1.156818
4,2MASS J23095781+5506472,primary,WDM,2MASS J23095781+5506472,0.14,104.100,4.70,5.3,1996725077535282944,60.921323,0.027054,2251.858643,13.986193,3.527839,0.0014,2930.619873,1.172912,False,False,3.526439
5,2MASS J23095848+5506491,companion,WDM,2MASS J23095781+5506472,NaN,NaN,4.70,5.3,1996725077535283200,60.894598,0.030128,2021.207642,15.604465,0.900766,NaN,NaN,1.034218,False,False,0.900766
6,G 68-34,primary,WDM,G 68-34,0.46,0.655,5.50,6.7,2826254717479033344,25.401530,0.027704,916.900330,12.907044,2.789584,0.0020,3007.359863,1.433894,False,True,2.787584
7,LP 463-28,companion,WDM,G 68-34,NaN,NaN,5.50,6.7,2826254713186397184,25.366649,0.099561,254.784164,17.682983,1.011217,NaN,NaN,1.044730,False,False,1.011217
8,GJ 1179 B,primary,WDM,GJ 1179 B,0.12,NaN,5.40,103.0,1251824057289839616,84.310524,0.028874,2919.910156,15.338058,1.268907,NaN,NaN,1.013633,False,False,1.268907
9,GJ 1179 A,companion,WDM,GJ 1179 B,NaN,NaN,5.40,103.0,1251824607045654016,84.224634,0.026624,3163.458252,13.441506,3.529751,NaN,NaN,1.209259,False,False,3.529751
10,GJ 283 B,primary,WDM,GJ 283 B,0.10,NaN,1.90,2.1,5717278911884264576,109.254482,0.039175,2788.894043,13.956890,4.379336,NaN,NaN,1.086701,True,False,4.379336
11,GJ 283 A,companion,WDM,GJ 283 B,NaN,NaN,1.90,2.1,5717278911884258304,109.343966,0.018101,6040.931641,12.970207,0.341712,NaN,NaN,1.022184,False,False,0.341712
12,GJ 754.1 B,primary,WDM,GJ 754.1 B,0.26,NaN,1.10,1.2,4201781696994082944,95.178395,0.031006,3069.674561,10.972157,2.561893,0.0000,3299.643066,1.169582,True,False,2.561893
13,GJ 754.1 A,companion,WDM,GJ 754.1 B,NaN,NaN,1.10,1.2,4201781696994073472,95.175778,0.029248,3254.068115,12.253493,0.036789,NaN,NaN,1.011426,True,False,0.036789
14,GJ 166 C,primary,WDM,GJ 166 C,0.24,NaN,0.63,3.6,3195919254111314944,199.451619,0.069206,2881.988770,9.775309,2.989676,NaN,NaN,1.531192,False,True,2.989676
15,GJ 166 B,companion,WDM,GJ 166 C,NaN,NaN,0.63,3.6,3195919254111315968,199.691073,0.051203,3899.964111,9.542240,-0.191004,NaN,NaN,1.195353,False,False,-0.191004
16,GJ 169.1 B,primary,WDM,GJ 169.1 B,0.31,NaN,2.80,3.1,470826482637310848,181.273007,0.020259,8947.962891,12.336190,0.442300,NaN,NaN,0.926382,True,False,0.442300
17,GJ 169.1 A,companion,WDM,GJ 169.1 B,NaN,NaN,2.80,3.1,470826482637310080,181.243839,0.049853,3635.564209,9.702565,2.895883,NaN,NaN,1.218251,False,False,2.895883
18,G 271-110,primary,FGKM,G 271-110,0.31,1.060,NaN,NaN,2478001486169801216,41.698927,0.044565,935.681396,12.708993,2.879617,NaN,NaN,1.708186,False,True,2.879617
19,HD 10008,companion,FGKM,G 271-110,NaN,7.100,NaN,NaN,2477815222028038144,41.563621,0.023779,1747.897461,7.465530,0.970934,0.0000,5186.510254,0.967905,False,False,0.970934
20,LP 99-392,primary,FGKM,LP 99-392,0.31,1.196,NaN,NaN,1603272950424941568,51.346175,0.019287,2662.232422,12.155627,2.776622,0.0000,3015.146240,1.356397,False,False,2.776622
21,HD 139477,companion,FGKM,LP 99-392,NaN,11.200,NaN,NaN,1603267143629157120,51.222192,0.017109,2993.855713,8.033153,1.292188,0.0000,4533.753418,0.968590,True,False,1.292188
22,LP 128-32,primary,FGKM,LP 128-32,0.32,6.500,NaN,NaN,837177915851182080,37.888516,0.027854,1360.244995,12.762718,2.794552,0.0000,3010.186035,1.414515,False,True,2.794552
23,HD 93811,companion,FGKM,LP 128-32,NaN,8.500,NaN,NaN,837178843564106112,NaN,NaN,NaN,8.047441,1.110751,NaN,NaN,NaN,False,False,1.110751
24,GJ 166 C,primary,FGKM,GJ 166 C,0.24,NaN,NaN,NaN,3195919254111314944,199.451619,0.069206,2881.988770,9.775309,2.989676,NaN,NaN,1.531192,False,True,2.989676
25,GJ 166 A,companion,FGKM,GJ 166 C,NaN,42.000,NaN,NaN,3195919528989222912,199.608012,0.120830,1651.970093,4.179894,1.041245,NaN,NaN,1.944932,False,True,1.041245
26,LP 876-10,primary,FGKM,LP 876-10,0.20,0.318,NaN,NaN,6623351805412369408,130.270657,0.032491,4009.497070,11.129232,3.014723,NaN,NaN,1.205662,False,False,3.014723
27,HD 216803,companion,FGKM,LP 876-10,NaN,10.100,NaN,NaN,6604147121141267456,131.552509,0.027515,4781.052734,6.091865,1.340312,0.0000,4463.108887,0.924698,False,False,1.340312
28,LSPM J0849+0329W,primary,FGKM,LSPM J0849+0329W,0.23,4.400,NaN,NaN,581103581886377728,32.950051,0.019860,1659.099365,13.747092,2.915384,NaN,NaN,1.083455,False,False,2.915384
29,HD 75302,companion,FGKM,LSPM J0849+0329W,NaN,16.400,NaN,NaN,581100382135253760,32.977697,0.023894,1380.154541,7.295366,0.850505,0.0000,5556.243164,1.003923,False,False,0.850505
30,G 232-62,primary,FGKM,G 232-62,0.27,59.000,NaN,NaN,2005804153064109056,45.625263,0.020282,2249.493408,12.732375,2.851560,0.0000,3000.069824,1.232156,True,False,2.851560
31,HD 211472,companion,FGKM,G 232-62,NaN,8.500,NaN,NaN,2005798350576886272,45.591305,0.016781,2716.801514,7.283160,0.988545,0.0000,5145.105957,1.011246,False,False,0.988545
32,2MASS J22562702+7600101,primary,FGKM,2MASS J22562702+7600101,0.19,2.510,NaN,NaN,2281128259862423552,40.764760,0.013567,3004.621338,13.652215,2.960724,0.0000,3120.958252,1.229958,False,False,2.960724
33,HD 217142,companion,FGKM,2MASS J22562702+7600101,NaN,20.300,NaN,NaN,2281114756485256704,40.682667,0.014321,2840.775391,8.001969,1.115376,NaN,NaN,0.932459,False,False,1.115376
34,2MASS J05363846+1117487,primary,FGKM,2MASS J05363846+1117487,0.29,5.300,NaN,NaN,3339914973377653760,87.345270,0.033755,2587.662842,11.196607,2.813897,NaN,NaN,1.226539,False,False,2.813897
35,HD 245409,companion,FGKM,2MASS J05363846+1117487,NaN,11.200,NaN,NaN,3339921875389105152,87.529740,0.024231,3612.245850,8.195061,1.815884,NaN,NaN,1.134360,False,False,1.815884
36,HD 183870 B,primary,FGKM,HD 183870 B,0.24,2.320,NaN,NaN,4187836934609063552,56.587143,0.027592,2050.872559,12.532383,2.867911,0.0000,3000.451904,1.258369,True,False,2.867911
37,HD 183870,companion,FGKM,HD 183870 B,NaN,NaN,NaN,NaN,4187837450005193216,56.565739,0.022709,2490.905518,7.265495,1.107620,0.0000,4866.604492,1.048768,False,False,1.107620

In [3]:
pass2022[pass2022['gaia_ruwe'] >= 1.4]

,name,role,binary_type,system_id,mass_msun,prot_days,age_min_gyr,age_c18_gyr,gaia_source_id,gaia_parallax,gaia_parallax_error,gaia_parallax_over_error,gaia_phot_g_mean_mag,gaia_bp_rp,gaia_ebpminrp_gspphot,gaia_teff_gspphot,gaia_ruwe,flag_multi_match,flag_high_ruwe,bprp0
2,LHS 2928,primary,WDM,LHS 2928,0.25,126.233,5.90,16.9,6272325816233230336,30.928890,0.108796,284.282928,13.776616,2.893877,NaN,NaN,5.506029,False,True,2.893877
6,G 68-34,primary,WDM,G 68-34,0.46,0.655,5.50,6.7,2826254717479033344,25.401530,0.027704,916.900330,12.907044,2.789584,0.002,3007.359863,1.433894,False,True,2.787584
14,GJ 166 C,primary,WDM,GJ 166 C,0.24,NaN,0.63,3.6,3195919254111314944,199.451619,0.069206,2881.988770,9.775309,2.989676,NaN,NaN,1.531192,False,True,2.989676
18,G 271-110,primary,FGKM,G 271-110,0.31,1.060,NaN,NaN,2478001486169801216,41.698927,0.044565,935.681396,12.708993,2.879617,NaN,NaN,1.708186,False,True,2.879617
22,LP 128-32,primary,FGKM,LP 128-32,0.32,6.500,NaN,NaN,837177915851182080,37.888516,0.027854,1360.244995,12.762718,2.794552,0.000,3010.186035,1.414515,False,True,2.794552
24,GJ 166 C,primary,FGKM,GJ 166 C,0.24,NaN,NaN,NaN,3195919254111314944,199.451619,0.069206,2881.988770,9.775309,2.989676,NaN,NaN,1.531192,False,True,2.989676
25,GJ 166 A,companion,FGKM,GJ 166 C,NaN,42.000,NaN,NaN,3195919528989222912,199.608012,0.120830,1651.970093,4.179894,1.041245,NaN,NaN,1.944932,False,True,1.041245

In [6]:
fgkm = p22[p22['binary_type'] == 'FGKM'].copy()
print(f'FGKM stars: {len(fgkm)}')

ids = fgkm['gaia_source_id'].dropna().astype('Int64').tolist()
ids_str = ', '.join(str(i) for i in ids)

query = f"""
SELECT source_id, phot_bp_mean_flux, phot_bp_mean_flux_error,
       phot_rp_mean_flux, phot_rp_mean_flux_error
FROM gaiadr3.gaia_source
WHERE source_id IN ({ids_str})
"""
flux_results = Gaia.launch_job(query).get_results().to_pandas()
flux_results['source_id'] = flux_results['source_id'].astype('Int64')
print(f'Returned: {len(flux_results)} rows')

FGKM stars: 20
Returned: 11 rows

In [7]:
returned_ids = set(flux_results['source_id'].tolist())
missing = fgkm[~fgkm['gaia_source_id'].isin(returned_ids)]
print(missing[['name', 'role', 'gaia_source_id']])

                       name       role       gaia_source_id
19                 HD 10008  companion  2477815222028038144
20                LP 99-392    primary  1603272950424941568
24                 GJ 166 C    primary  3195919254111314944
25                 GJ 166 A  companion  3195919528989222912
26                LP 876-10    primary  6623351805412369408
27                HD 216803  companion  6604147121141267456
31                HD 211472  companion  2005798350576886272
32  2MASS J22562702+7600101    primary  2281128259862423552
37                HD 183870  companion  4187837450005193216

In [10]:
import numpy as np

flux_results['sigma_bprp'] = (2.5 / np.log(10)) * np.sqrt(
    (flux_results['phot_bp_mean_flux_error'] / flux_results['phot_bp_mean_flux'])**2 +
    (flux_results['phot_rp_mean_flux_error'] / flux_results['phot_rp_mean_flux'])**2
)
flux_results['logCerr'] = np.log10(flux_results['sigma_bprp'])

fgkm = fgkm.merge(
    flux_results[['source_id', 'logCerr']].rename(columns={'source_id': 'gaia_source_id'}),
    on='gaia_source_id',
    how='left'
)
fgkm['logCerr'] = fgkm['logCerr'].fillna(-1.55)

In [13]:
fgk = fgkm[fgkm['role'] == 'companion'].copy()
print(f'FGK companions: {len(fgk)}')
print(fgk[['name', 'prot_days', 'bprp0', 'logCerr']])
fgk = fgk[fgk['prot_days'].notna()].copy()
fgk

FGK companions: 10
         name  prot_days     bprp0   logCerr
1    HD 10008        7.1  0.970934 -1.550000
3   HD 139477       11.2  1.292188 -2.845941
5    HD 93811        8.5  1.110751 -2.723216
7    GJ 166 A       42.0  1.041245 -1.550000
9   HD 216803       10.1  1.340312 -1.550000
11   HD 75302       16.4  0.850505 -2.705118
13  HD 211472        8.5  0.988545 -1.550000
15  HD 217142       20.3  1.115376 -2.677045
17  HD 245409       11.2  1.815884 -2.584341
19  HD 183870        NaN  1.107620 -1.550000

,name,role,binary_type,system_id,mass_msun,prot_days,age_min_gyr,age_c18_gyr,gaia_source_id,gaia_parallax,...,gaia_bp_rp,gaia_ebpminrp_gspphot,gaia_teff_gspphot,gaia_ruwe,flag_multi_match,flag_high_ruwe,bprp0,logCerr_x,logCerr_y,logCerr
1,HD 10008,companion,FGKM,G 271-110,NaN,7.1,NaN,NaN,2477815222028038144,41.563621,...,0.970934,0.0,5186.510254,0.967905,False,False,0.970934,-1.550000,NaN,-1.550000
3,HD 139477,companion,FGKM,LP 99-392,NaN,11.2,NaN,NaN,1603267143629157120,51.222192,...,1.292188,0.0,4533.753418,0.968590,True,False,1.292188,-2.845941,-2.845941,-2.845941
5,HD 93811,companion,FGKM,LP 128-32,NaN,8.5,NaN,NaN,837178843564106112,NaN,...,1.110751,NaN,NaN,NaN,False,False,1.110751,-2.723216,-2.723216,-2.723216
7,GJ 166 A,companion,FGKM,GJ 166 C,NaN,42.0,NaN,NaN,3195919528989222912,199.608012,...,1.041245,NaN,NaN,1.944932,False,True,1.041245,-1.550000,NaN,-1.550000
9,HD 216803,companion,FGKM,LP 876-10,NaN,10.1,NaN,NaN,6604147121141267456,131.552509,...,1.340312,0.0,4463.108887,0.924698,False,False,1.340312,-1.550000,NaN,-1.550000
11,HD 75302,companion,FGKM,LSPM J0849+0329W,NaN,16.4,NaN,NaN,581100382135253760,32.977697,...,0.850505,0.0,5556.243164,1.003923,False,False,0.850505,-2.705118,-2.705118,-2.705118
13,HD 211472,companion,FGKM,G 232-62,NaN,8.5,NaN,NaN,2005798350576886272,45.591305,...,0.988545,0.0,5145.105957,1.011246,False,False,0.988545,-1.550000,NaN,-1.550000
15,HD 217142,companion,FGKM,2MASS J22562702+7600101,NaN,20.3,NaN,NaN,2281114756485256704,40.682667,...,1.115376,NaN,NaN,0.932459,False,False,1.115376,-2.677045,-2.677045,-2.677045
17,HD 245409,companion,FGKM,2MASS J05363846+1117487,NaN,11.2,NaN,NaN,3339921875389105152,87.529740,...,1.815884,NaN,NaN,1.134360,False,False,1.815884,-2.584341,-2.584341,-2.584341

In [24]:
import pandas as pd
import sys
sys.path.insert(0, '.')
from chronoflow.ChronoFlow import ChronoFlow
import numpy as np

fgkm = pd.read_csv('cf_data/pass2022_fgkm.csv')

# need logCerr — repull BP/RP fluxes for companions with prot_days
from astroquery.gaia import Gaia

companions = fgkm[(fgkm['role'] == 'companion') & fgkm['prot_days'].notna()].copy()
ids_str = ', '.join(str(i) for i in companions['source_id'].astype('Int64').tolist())

flux_results = Gaia.launch_job(f"""
    SELECT source_id, phot_bp_mean_flux, phot_bp_mean_flux_error,
           phot_rp_mean_flux, phot_rp_mean_flux_error
    FROM gaiadr3.gaia_source
    WHERE source_id IN ({ids_str})
""").get_results().to_pandas()

flux_results['source_id'] = flux_results['source_id'].astype('Int64')
flux_results['sigma_bprp'] = (2.5 / np.log(10)) * np.sqrt(
    (flux_results['phot_bp_mean_flux_error'] / flux_results['phot_bp_mean_flux'])**2 +
    (flux_results['phot_rp_mean_flux_error'] / flux_results['phot_rp_mean_flux'])**2
)
flux_results['logCerr'] = np.log10(flux_results['sigma_bprp'])

companions = companions.merge(
    flux_results[['source_id', 'logCerr']],
    on='source_id',
    how='left'
)
companions['logCerr'] = companions['logCerr'].fillna(-1.55)

fgk = companions.copy()
print(f'running ChronoFlow on {len(fgk)} FGK companions')
print(fgk[['name', 'prot_days', 'bprp0', 'logCerr']])

# ChronoFlow inference
WEIGHTS_BPRP = 'model_output_BPRP_0/weights.pth'
cf_model = ChronoFlow(weights_file=WEIGHTS_BPRP)
logA_grid = np.linspace(0, 4.14, 1000)

results = []
for _, row in fgk.iterrows():
    post = cf_model.calcPostAge(
        logProt=np.log10(float(row['prot_days'])),
        BPRP0=float(row['bprp0']),
        logCerr=float(row['logCerr'])
    )
    medLogA, logA_Err, logA_err = cf_model.getAgeSummStats(post, logA_grid)
    age_gyr = 10**medLogA / 1000
    age_gyr_upper = (10**(medLogA + logA_Err) / 1000) - age_gyr
    age_gyr_lower = age_gyr - (10**(medLogA + logA_err) / 1000)
    results.append({
        'name': row['name'],
        'prot_days': row['prot_days'],
        'bprp0': row['bprp0'],
        'medLogA_Myr': medLogA,
        'age_gyr_cf': age_gyr,
        'age_gyr_upper': age_gyr_upper,
        'age_gyr_lower': age_gyr_lower
    })

results_df = pd.DataFrame(results)
print(results_df)

running ChronoFlow on 9 FGK companions
        name  prot_days     bprp0   logCerr
0   HD 10008        7.1  0.970934 -2.814617
1  HD 139477       11.2  1.292188 -2.845941
2   HD 93811        8.5  1.110751 -2.723216
3   GJ 166 A       42.0  1.041245 -2.514532
4  HD 216803       10.1  1.340312 -2.326921
5   HD 75302       16.4  0.850505 -2.705118
6  HD 211472        8.5  0.988545 -2.809264
7  HD 217142       20.3  1.115376 -2.677045
8  HD 245409       11.2  1.815884 -2.584341
        name  prot_days     bprp0  medLogA_Myr  age_gyr_cf  age_gyr_upper  \
0   HD 10008        7.1  0.970934     2.432613    0.270778       0.187579
1  HD 139477       11.2  1.292188     2.507207    0.321519       0.063911
2   HD 93811        8.5  1.110751     2.353874    0.225878       0.083601
3   GJ 166 A       42.0  1.041245     3.870631    7.423875       0.512819
4  HD 216803       10.1  1.340312     2.341441    0.219503       0.046155
5   HD 75302       16.4  0.850505     3.605405    4.030931       0.532371
6  HD 211472        8.5  0.988545     2.631532    0.428086       0.198956
7  HD 217142       20.3  1.115376     3.369189    2.339856       0.185614
8  HD 245409       11.2  1.815884     2.333153    0.215354       0.047782

   age_gyr_lower
0       0.127903
1       0.060882
2       0.070191
3       0.545632
4       0.034642
5       0.504078
6       0.179593
7       0.192560
8       0.050745

In [ ]:
fgkm = pd.read_csv('cf_data/pass2022_fgkm.csv')

# update companion rows with new cf ages
fgkm = fgkm.merge(
    results_df[['name', 'age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']],
    on='name',
    how='left',
    suffixes=('_old', '')
)
fgkm = fgkm.drop(columns=['age_gyr_cf_old', 'age_gyr_upper_old', 'age_gyr_lower_old'])

# propagate companion ages to their paired primary (always the row above)
for i in range(1, len(fgkm), 2):  # companion rows are odd indices
    for col in ['age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']:
        val = fgkm.at[i, col]
        if pd.notna(val):
            fgkm.at[i-1, col] = val

fgkm.to_csv('cf_data/pass2022_fgkm.csv', index=False)
print('saved!')
fgkm[['name', 'role', 'age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']]

saved!

,name,role,age_gyr_cf,age_gyr_upper,age_gyr_lower
0,G 271-110,primary,0.270778,0.187579,0.127903
1,HD 10008,companion,0.270778,0.187579,0.127903
2,LP 99-392,primary,0.321519,0.063911,0.060882
3,HD 139477,companion,0.321519,0.063911,0.060882
4,LP 128-32,primary,0.225878,0.083601,0.070191
5,HD 93811,companion,0.225878,0.083601,0.070191
6,GJ 166 C,primary,7.423875,0.512819,0.545632
7,GJ 166 A,companion,7.423875,0.512819,0.545632
8,LP 876-10,primary,0.219503,0.046155,0.034642
9,HD 216803,companion,0.219503,0.046155,0.034642
10,LSPM J0849+0329W,primary,4.030931,0.532371,0.504078
11,HD 75302,companion,4.030931,0.532371,0.504078
12,G 232-62,primary,0.428086,0.198956,0.179593
13,HD 211472,companion,0.428086,0.198956,0.179593
14,2MASS J22562702+7600101,primary,2.339856,0.185614,0.192560
15,HD 217142,companion,2.339856,0.185614,0.192560
16,2MASS J05363846+1117487,primary,0.215354,0.047782,0.050745
17,HD 245409,companion,0.215354,0.047782,0.050745
18,HD 183870 B,primary,NaN,NaN,NaN
19,HD 183870,companion,NaN,NaN,NaN

In [26]:
fgkm = pd.read_csv('cf_data/pass2022_fgkm.csv')

# update companion rows with new cf ages
fgkm = fgkm.merge(
    results_df[['name', 'age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']],
    on='name',
    how='left',
    suffixes=('_old', '')
)
fgkm = fgkm.drop(columns=['age_gyr_cf_old', 'age_gyr_upper_old', 'age_gyr_lower_old'])

# propagate companion ages to their paired primary (always the row above)
for i in range(1, len(fgkm), 2):  # companion rows are odd indices
    for col in ['age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']:
        val = fgkm.at[i, col]
        if pd.notna(val):
            fgkm.at[i-1, col] = val

fgkm.to_csv('cf_data/pass2022_fgkm.csv', index=False)
print('saved!')
fgkm[['name', 'role', 'age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']]

saved!

,name,role,age_gyr_cf,age_gyr_upper,age_gyr_lower
0,G 271-110,primary,0.270778,0.187579,0.127903
1,HD 10008,companion,0.270778,0.187579,0.127903
2,LP 99-392,primary,0.321519,0.063911,0.060882
3,HD 139477,companion,0.321519,0.063911,0.060882
4,LP 128-32,primary,0.225878,0.083601,0.070191
5,HD 93811,companion,0.225878,0.083601,0.070191
6,GJ 166 C,primary,7.423875,0.512819,0.545632
7,GJ 166 A,companion,7.423875,0.512819,0.545632
8,LP 876-10,primary,0.219503,0.046155,0.034642
9,HD 216803,companion,0.219503,0.046155,0.034642
10,LSPM J0849+0329W,primary,4.030931,0.532371,0.504078
11,HD 75302,companion,4.030931,0.532371,0.504078
12,G 232-62,primary,0.428086,0.198956,0.179593
13,HD 211472,companion,0.428086,0.198956,0.179593
14,2MASS J22562702+7600101,primary,2.339856,0.185614,0.192560
15,HD 217142,companion,2.339856,0.185614,0.192560
16,2MASS J05363846+1117487,primary,0.215354,0.047782,0.050745
17,HD 245409,companion,0.215354,0.047782,0.050745
18,HD 183870 B,primary,NaN,NaN,NaN
19,HD 183870,companion,NaN,NaN,NaN

In [20]:
fgkm = pd.read_csv('cf_data/pass2022_fgkm.csv')
fgkm

,name,role,binary_type,system_id,mass_msun,prot_days,age_min_gyr,age_c18_gyr,gaia_source_id,gaia_parallax,...,gaia_bp_rp,gaia_ebpminrp_gspphot,gaia_teff_gspphot,gaia_ruwe,flag_multi_match,flag_high_ruwe,bprp0,age_gyr_cf,age_gyr_upper,age_gyr_lower
0,G 271-110,primary,FGKM,G 271-110,0.31,1.060,NaN,NaN,2478001486169801216,41.698927,...,2.879617,NaN,NaN,1.708186,False,True,2.879617,0.438422,NaN,NaN
1,HD 10008,companion,FGKM,G 271-110,NaN,7.100,NaN,NaN,2477815222028038144,41.563621,...,0.970934,0.0,5186.510254,0.967905,False,False,0.970934,0.438422,0.126141,0.146164
2,LP 99-392,primary,FGKM,LP 99-392,0.31,1.196,NaN,NaN,1603272950424941568,51.346175,...,2.776622,0.0,3015.146240,1.356397,False,False,2.776622,0.327714,NaN,NaN
3,HD 139477,companion,FGKM,LP 99-392,NaN,11.200,NaN,NaN,1603267143629157120,51.222192,...,1.292188,0.0,4533.753418,0.968590,True,False,1.292188,0.327714,0.061411,0.064578
4,LP 128-32,primary,FGKM,LP 128-32,0.32,6.500,NaN,NaN,837177915851182080,37.888516,...,2.794552,0.0,3010.186035,1.414515,False,True,2.794552,0.230230,NaN,NaN
5,HD 93811,companion,FGKM,LP 128-32,NaN,8.500,NaN,NaN,837178843564106112,NaN,...,1.110751,NaN,NaN,NaN,False,False,1.110751,0.230230,0.085211,0.081797
6,GJ 166 C,primary,FGKM,GJ 166 C,0.24,NaN,NaN,NaN,3195919254111314944,199.451619,...,2.989676,NaN,NaN,1.531192,False,True,2.989676,6.433814,NaN,NaN
7,GJ 166 A,companion,FGKM,GJ 166 C,NaN,42.000,NaN,NaN,3195919528989222912,199.608012,...,1.041245,NaN,NaN,1.944932,False,True,1.041245,6.433814,1.278900,1.066837
8,LP 876-10,primary,FGKM,LP 876-10,0.20,0.318,NaN,NaN,6623351805412369408,130.270657,...,3.014723,NaN,NaN,1.205662,False,False,3.014723,0.513181,NaN,NaN
9,HD 216803,companion,FGKM,LP 876-10,NaN,10.100,NaN,NaN,6604147121141267456,131.552509,...,1.340312,0.0,4463.108887,0.924698,False,False,1.340312,0.513181,0.157177,0.194715
10,LSPM J0849+0329W,primary,FGKM,LSPM J0849+0329W,0.23,4.400,NaN,NaN,581103581886377728,32.950051,...,2.915384,NaN,NaN,1.083455,False,False,2.915384,4.030931,NaN,NaN
11,HD 75302,companion,FGKM,LSPM J0849+0329W,NaN,16.400,NaN,NaN,581100382135253760,32.977697,...,0.850505,0.0,5556.243164,1.003923,False,False,0.850505,4.030931,0.495940,0.504078
12,G 232-62,primary,FGKM,G 232-62,0.27,59.000,NaN,NaN,2005804153064109056,45.625263,...,2.851560,0.0,3000.069824,1.232156,True,False,2.851560,0.627043,NaN,NaN
13,HD 211472,companion,FGKM,G 232-62,NaN,8.500,NaN,NaN,2005798350576886272,45.591305,...,0.988545,0.0,5145.105957,1.011246,False,False,0.988545,0.627043,0.161375,0.230420
14,2MASS J22562702+7600101,primary,FGKM,2MASS J22562702+7600101,0.19,2.510,NaN,NaN,2281128259862423552,40.764760,...,2.960724,0.0,3120.958252,1.229958,False,False,2.960724,2.362291,NaN,NaN
15,HD 217142,companion,FGKM,2MASS J22562702+7600101,NaN,20.300,NaN,NaN,2281114756485256704,40.682667,...,1.115376,NaN,NaN,0.932459,False,False,1.115376,2.362291,0.187394,0.194407
16,2MASS J05363846+1117487,primary,FGKM,2MASS J05363846+1117487,0.29,5.300,NaN,NaN,3339914973377653760,87.345270,...,2.813897,NaN,NaN,1.226539,False,False,2.813897,0.215354,NaN,NaN
17,HD 245409,companion,FGKM,2MASS J05363846+1117487,NaN,11.200,NaN,NaN,3339921875389105152,87.529740,...,1.815884,NaN,NaN,1.134360,False,False,1.815884,0.215354,0.045681,0.048913
18,HD 183870 B,primary,FGKM,HD 183870 B,0.24,2.320,NaN,NaN,4187836934609063552,56.587143,...,2.867911,0.0,3000.451904,1.258369,True,False,2.867911,NaN,NaN,NaN
19,HD 183870,companion,FGKM,HD 183870 B,NaN,NaN,NaN,NaN,4187837450005193216,56.565739,...,1.107620,0.0,4866.604492,1.048768,False,False,1.107620,NaN,NaN,NaN

In [21]:
for sys_id in fgkm['system_id'].unique():
    companion = fgkm[(fgkm['system_id'] == sys_id) & (fgkm['role'] == 'companion')]
    if len(companion) > 0:
        for col in ['age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']:
            val = companion[col].values[0]
            if not pd.isna(val):
                fgkm.loc[(fgkm['system_id'] == sys_id) & 
                         (fgkm['role'] == 'primary'), col] = val

print(fgkm[['name', 'role', 'age_gyr_cf', 'age_gyr_upper', 'age_gyr_lower']])
fgkm.to_csv('cf_data/pass2022_fgkm.csv', index=False)
print('Saved!')

                       name       role  age_gyr_cf  age_gyr_upper  \
0                 G 271-110    primary    0.438422       0.126141
1                  HD 10008  companion    0.438422       0.126141
2                 LP 99-392    primary    0.327714       0.061411
3                 HD 139477  companion    0.327714       0.061411
4                 LP 128-32    primary    0.230230       0.085211
5                  HD 93811  companion    0.230230       0.085211
6                  GJ 166 C    primary    6.433814       1.278900
7                  GJ 166 A  companion    6.433814       1.278900
8                 LP 876-10    primary    0.513181       0.157177
9                 HD 216803  companion    0.513181       0.157177
10         LSPM J0849+0329W    primary    4.030931       0.495940
11                 HD 75302  companion    4.030931       0.495940
12                 G 232-62    primary    0.627043       0.161375
13                HD 211472  companion    0.627043       0.161375
14  2MASS J22562702+7600101    primary    2.362291       0.187394
15                HD 217142  companion    2.362291       0.187394
16  2MASS J05363846+1117487    primary    0.215354       0.045681
17                HD 245409  companion    0.215354       0.045681
18              HD 183870 B    primary         NaN            NaN
19                HD 183870  companion         NaN            NaN

    age_gyr_lower
0        0.146164
1        0.146164
2        0.064578
3        0.064578
4        0.081797
5        0.081797
6        1.066837
7        1.066837
8        0.194715
9        0.194715
10       0.504078
11       0.504078
12       0.230420
13       0.230420
14       0.194407
15       0.194407
16       0.048913
17       0.048913
18            NaN
19            NaN
Saved!

In [22]:
fgkm

,name,role,binary_type,system_id,mass_msun,prot_days,age_min_gyr,age_c18_gyr,gaia_source_id,gaia_parallax,...,gaia_bp_rp,gaia_ebpminrp_gspphot,gaia_teff_gspphot,gaia_ruwe,flag_multi_match,flag_high_ruwe,bprp0,age_gyr_cf,age_gyr_upper,age_gyr_lower
0,G 271-110,primary,FGKM,G 271-110,0.31,1.060,NaN,NaN,2478001486169801216,41.698927,...,2.879617,NaN,NaN,1.708186,False,True,2.879617,0.438422,0.126141,0.146164
1,HD 10008,companion,FGKM,G 271-110,NaN,7.100,NaN,NaN,2477815222028038144,41.563621,...,0.970934,0.0,5186.510254,0.967905,False,False,0.970934,0.438422,0.126141,0.146164
2,LP 99-392,primary,FGKM,LP 99-392,0.31,1.196,NaN,NaN,1603272950424941568,51.346175,...,2.776622,0.0,3015.146240,1.356397,False,False,2.776622,0.327714,0.061411,0.064578
3,HD 139477,companion,FGKM,LP 99-392,NaN,11.200,NaN,NaN,1603267143629157120,51.222192,...,1.292188,0.0,4533.753418,0.968590,True,False,1.292188,0.327714,0.061411,0.064578
4,LP 128-32,primary,FGKM,LP 128-32,0.32,6.500,NaN,NaN,837177915851182080,37.888516,...,2.794552,0.0,3010.186035,1.414515,False,True,2.794552,0.230230,0.085211,0.081797
5,HD 93811,companion,FGKM,LP 128-32,NaN,8.500,NaN,NaN,837178843564106112,NaN,...,1.110751,NaN,NaN,NaN,False,False,1.110751,0.230230,0.085211,0.081797
6,GJ 166 C,primary,FGKM,GJ 166 C,0.24,NaN,NaN,NaN,3195919254111314944,199.451619,...,2.989676,NaN,NaN,1.531192,False,True,2.989676,6.433814,1.278900,1.066837
7,GJ 166 A,companion,FGKM,GJ 166 C,NaN,42.000,NaN,NaN,3195919528989222912,199.608012,...,1.041245,NaN,NaN,1.944932,False,True,1.041245,6.433814,1.278900,1.066837
8,LP 876-10,primary,FGKM,LP 876-10,0.20,0.318,NaN,NaN,6623351805412369408,130.270657,...,3.014723,NaN,NaN,1.205662,False,False,3.014723,0.513181,0.157177,0.194715
9,HD 216803,companion,FGKM,LP 876-10,NaN,10.100,NaN,NaN,6604147121141267456,131.552509,...,1.340312,0.0,4463.108887,0.924698,False,False,1.340312,0.513181,0.157177,0.194715
10,LSPM J0849+0329W,primary,FGKM,LSPM J0849+0329W,0.23,4.400,NaN,NaN,581103581886377728,32.950051,...,2.915384,NaN,NaN,1.083455,False,False,2.915384,4.030931,0.495940,0.504078
11,HD 75302,companion,FGKM,LSPM J0849+0329W,NaN,16.400,NaN,NaN,581100382135253760,32.977697,...,0.850505,0.0,5556.243164,1.003923,False,False,0.850505,4.030931,0.495940,0.504078
12,G 232-62,primary,FGKM,G 232-62,0.27,59.000,NaN,NaN,2005804153064109056,45.625263,...,2.851560,0.0,3000.069824,1.232156,True,False,2.851560,0.627043,0.161375,0.230420
13,HD 211472,companion,FGKM,G 232-62,NaN,8.500,NaN,NaN,2005798350576886272,45.591305,...,0.988545,0.0,5145.105957,1.011246,False,False,0.988545,0.627043,0.161375,0.230420
14,2MASS J22562702+7600101,primary,FGKM,2MASS J22562702+7600101,0.19,2.510,NaN,NaN,2281128259862423552,40.764760,...,2.960724,0.0,3120.958252,1.229958,False,False,2.960724,2.362291,0.187394,0.194407
15,HD 217142,companion,FGKM,2MASS J22562702+7600101,NaN,20.300,NaN,NaN,2281114756485256704,40.682667,...,1.115376,NaN,NaN,0.932459,False,False,1.115376,2.362291,0.187394,0.194407
16,2MASS J05363846+1117487,primary,FGKM,2MASS J05363846+1117487,0.29,5.300,NaN,NaN,3339914973377653760,87.345270,...,2.813897,NaN,NaN,1.226539,False,False,2.813897,0.215354,0.045681,0.048913
17,HD 245409,companion,FGKM,2MASS J05363846+1117487,NaN,11.200,NaN,NaN,3339921875389105152,87.529740,...,1.815884,NaN,NaN,1.134360,False,False,1.815884,0.215354,0.045681,0.048913
18,HD 183870 B,primary,FGKM,HD 183870 B,0.24,2.320,NaN,NaN,4187836934609063552,56.587143,...,2.867911,0.0,3000.451904,1.258369,True,False,2.867911,NaN,NaN,NaN
19,HD 183870,companion,FGKM,HD 183870 B,NaN,NaN,NaN,NaN,4187837450005193216,56.565739,...,1.107620,0.0,4866.604492,1.048768,False,False,1.107620,NaN,NaN,NaN